"""Collision contacts for the isolated viewport runtime."""
from __future__ import annotations

import math
from typing import Any, Callable

try:
    from engine.physics.spatial_hash import BroadPhaseStats, SpatialHashBroadPhase
except ModuleNotFoundError:  # Standalone runtime generated by the exporter.
    from .spatial_hash import BroadPhaseStats, SpatialHashBroadPhase


class ViewportContactProcessor:
    """Track contact transitions using a spatial broad phase."""

    def __init__(
        self,
        objects: dict[str, dict[str, Any]],
        active_contacts: dict[tuple[str, str], bool],
        dispatch: Callable[[str, str, str], None],
        *,
        cell_size: float = 128.0,
    ) -> None:
        self.objects = objects
        self.active_contacts = active_contacts
        self.dispatch = dispatch
        self.broad_phase = SpatialHashBroadPhase(cell_size=cell_size)

    @property
    def stats(self) -> BroadPhaseStats:
        return self.broad_phase.stats

    def process(self) -> None:
        collidable = [
            (name, obj, self.collider_bounds(obj)) for name, obj in self.objects.items()
            if obj.get("active", True) and isinstance(obj.get("collider"), dict)
        ]
        pairs = self.broad_phase.candidate_pairs(
            collidable,
            lambda item: item[2],
            lambda _item: self.objects,
        )
        current: dict[tuple[str, str], bool] = {}
        for (name_a, obj_a, bounds_a), (name_b, obj_b, bounds_b) in pairs:
            if not self._overlaps(bounds_a, bounds_b):
                continue
            pair = tuple(sorted((name_a, name_b)))
            is_trigger = bool(obj_a["collider"].get("is_trigger") or obj_b["collider"].get("is_trigger"))
            current[pair] = is_trigger
            if pair not in self.active_contacts:
                hook = "on_trigger" if is_trigger else "on_collision"
                self.dispatch(name_a, name_b, hook)
                self.dispatch(name_b, name_a, hook)
        for pair, was_trigger in list(self.active_contacts.items()):
            if pair not in current:
                hook = "on_trigger_exit" if was_trigger else "on_collision_exit"
                self.dispatch(pair[0], pair[1], hook)
                self.dispatch(pair[1], pair[0], hook)
        self.active_contacts.clear()
        self.active_contacts.update(current)

    @staticmethod
    def collider_bounds(obj: dict[str, Any]) -> tuple[float, float, float, float]:
        collider = obj.get("collider") or {}
        angle = math.radians(float(obj.get("rotation", 0.0)))
        offset_x = float(collider.get("offset_x", 0.0))
        offset_y = float(collider.get("offset_y", 0.0))
        cosine, sine = math.cos(angle), math.sin(angle)
        center_x = float(obj.get("x", 0.0)) + offset_x * cosine - offset_y * sine
        center_y = float(obj.get("y", 0.0)) + offset_x * sine + offset_y * cosine
        if str(collider.get("type", "box")).lower() == "circle":
            width = height = float(collider.get("radius", min(obj.get("w", 1.0), obj.get("h", 1.0)) / 2.0)) * 2.0
        else:
            width = float(collider.get("width", obj.get("w", 1.0)))
            height = float(collider.get("height", obj.get("h", 1.0)))
            abs_cosine, abs_sine = abs(cosine), abs(sine)
            width, height = width * abs_cosine + height * abs_sine, width * abs_sine + height * abs_cosine
        return center_x - width / 2.0, center_y - height / 2.0, center_x + width / 2.0, center_y + height / 2.0

    @staticmethod
    def _overlaps(first: tuple[float, float, float, float], second: tuple[float, float, float, float]) -> bool:
        left_a, top_a, right_a, bottom_a = first
        left_b, top_b, right_b, bottom_b = second
        return not (right_a < left_b or right_b < left_a or bottom_a < top_b or bottom_b < top_a)
