"""Play Mode runtime initialization for the isolated viewport."""
from __future__ import annotations

from pathlib import Path
from typing import Any, Callable

try:
    from engine.animation.controller_asset import AnimatorControllerRuntime
    from engine.logic.blackboard import BlackboardStore, load_blackboard_asset
    from engine.logic.event_bus import LogicEventBus
    from engine.logic.runtime import LogicGraphRuntime
except ModuleNotFoundError:  # Standalone runtime generated by the exporter.
    from .controller_asset import AnimatorControllerRuntime
    from .logic_blackboard import BlackboardStore, load_blackboard_asset
    from .logic_event_bus import LogicEventBus
    from .logic_runtime import LogicGraphRuntime

Hydrator = Callable[[dict[str, dict[str, Any]], Path], list[tuple[str, str, str]]]


class ViewportRuntimeInitializer:
    """Build, incrementally extend and tear down a Play Mode runtime session."""

    def __init__(
        self,
        objects: dict[str, dict[str, Any]],
        script_instances: dict[str, Any],
        script_apis: dict[str, Any],
        animator_controllers: dict[str, Any],
        behavior_runners: dict[str, Any],
        logic_runtimes: dict[str, list[tuple[str, Any]]],
        initialized_ids: set[str],
        animator_event_signatures: dict[str, Any],
        runtime_world: Any,
        hydrators: tuple[Hydrator, ...],
        api_factory: Callable[[str, dict[str, Any]], Any],
        subgraph_loader: Callable[[str], dict[str, Any]],
        emit: Callable[[dict[str, Any]], None],
        play_audio: Callable[..., None],
        project_root: Path,
    ) -> None:
        self.objects = objects
        self.script_instances = script_instances
        self.script_apis = script_apis
        self.animator_controllers = animator_controllers
        self.behavior_runners = behavior_runners
        self.logic_runtimes = logic_runtimes
        self.initialized_ids = initialized_ids
        self.animator_event_signatures = animator_event_signatures
        self.runtime_world = runtime_world
        self.hydrators = hydrators
        self.api_factory = api_factory
        self.subgraph_loader = subgraph_loader
        self.emit = emit
        self.play_audio = play_audio
        self.project_root = project_root
        self.logic_blackboard = BlackboardStore()
        self.logic_event_bus = LogicEventBus()

    def start(self, scene_blackboard: dict[str, Any] | None = None) -> None:
        self._clear_runtime_state()
        self.runtime_world.reset_session()
        self._create_logic_services(scene_blackboard or {})
        initial_objects = list(self.objects.items())
        self._hydrate(self.objects)
        for name, obj in initial_objects:
            self._initialize_animation(name, obj)
        for name, obj in initial_objects:
            self._initialize_logic(name, obj)
        self.initialized_ids.update(str(obj.get("id", name)) for name, obj in initial_objects)
        self.start_spawned_objects()
        loaded = sum(len(entries) for entries in self.logic_runtimes.values())
        self.emit({
            "type": "runtime_log", "level": "INFO",
            "message": f"Play Mode carregou {loaded} Logic Graph(s); scripts Python estão desativados",
        })

    def stop(self, active_contacts: dict[Any, Any]) -> None:
        self._clear_runtime_state()
        active_contacts.clear()
        self.emit({"type": "logic_trace_clear"})

    def start_spawned_objects(self) -> None:
        active_names = set(self.objects)
        for stale_name in set(self.logic_runtimes) - active_names:
            self.logic_runtimes.pop(stale_name, None)
            self.script_apis.pop(stale_name, None)
            self.animator_controllers.pop(stale_name, None)
        pending = [
            (name, obj) for name, obj in list(self.objects.items())
            if str(obj.get("id", name)) not in self.initialized_ids
        ]
        for name, obj in pending:
            self.initialized_ids.add(str(obj.get("id", name)))
            self._hydrate({name: obj})
            self._initialize_animation(name, obj)
            self._initialize_logic(name, obj)
            audio = obj.get("audio")
            if isinstance(audio, dict) and audio.get("autoplay") and audio.get("path"):
                self.play_audio(
                    name, str(audio["path"]), float(audio.get("volume", 1.0)),
                    bool(audio.get("loop", False)),
                )

    def _clear_runtime_state(self) -> None:
        self.logic_runtimes.clear()
        self.script_instances.clear()
        self.script_apis.clear()
        self.animator_controllers.clear()
        self.behavior_runners.clear()
        self.initialized_ids.clear()
        self.animator_event_signatures.clear()

    def _create_logic_services(self, scene_blackboard: dict[str, Any]) -> None:
        path = self.project_root / "Assets" / "Logic" / "ProjectBlackboard.zblackboard"
        try:
            project_blackboard = load_blackboard_asset(path) if path.is_file() else {}
        except (OSError, ValueError):
            project_blackboard = {}
        self.logic_blackboard = BlackboardStore(scene_blackboard, project_blackboard)
        self.logic_event_bus = LogicEventBus()

    def _hydrate(self, selected: dict[str, dict[str, Any]]) -> None:
        for hydrator in self.hydrators:
            for level, object_name, message in hydrator(selected, self.project_root):
                self.emit({
                    "type": "runtime_log", "level": level,
                    "message": f"{object_name}: {message}",
                })

    def _initialize_animation(self, name: str, obj: dict[str, Any]) -> None:
        animator = obj.get("animator")
        if not isinstance(animator, dict):
            return
        controller = animator.get("controller")
        if isinstance(controller, dict):
            runtime = AnimatorControllerRuntime(controller, animator.get("parameters", {}))
            self.animator_controllers[name] = runtime
            animator["parameters"] = dict(runtime.parameters)
            animator["active_clip"] = runtime.current_state
            obj["_animator_state"] = runtime.current_state
        obj["_current_animation_name"] = str(animator.get("active_clip", "Idle"))
        obj["_animation_time"], obj["_animation_frame"], obj["_animation_raw_frame"] = 0.0, 0, -1

    def _initialize_logic(self, name: str, obj: dict[str, Any]) -> None:
        entries = obj.get("logic_graphs", [])
        if not isinstance(entries, list):
            return
        for entry in entries:
            graph = entry.get("graph") if isinstance(entry, dict) else None
            if not isinstance(graph, dict):
                continue
            try:
                api = self.script_apis.setdefault(name, self.api_factory(name, obj))
                runtime = LogicGraphRuntime(
                    graph, self.logic_blackboard, name, self.logic_event_bus,
                    self.subgraph_loader,
                )
                runtime.start(api)
                path = str(entry.get("path", graph.get("name", "Logic Graph")))
                self.logic_runtimes.setdefault(name, []).append((path, runtime))
            except Exception as exc:
                self.emit({
                    "type": "runtime_log", "level": "ERROR",
                    "message": f"{name}: Logic Graph: {exc}",
                })
