"""Play Mode runtime initialization for the isolated viewport."""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Callable

from engine.diagnostics import get_logger, report_error, swallow

log = get_logger("runtime")

try:
    from engine.animation.controller_asset import AnimatorControllerRuntime
    from engine.behavior.controller_asset import BehaviorControllerRunner
    from engine.behavior.graph_runtime import BehaviorGraphRunner
    from engine.dialogue.runtime import DialogueSession
    from engine.logic.blackboard import BlackboardStore, load_blackboard_asset
    from engine.logic.event_bus import LogicEventBus
    from engine.logic.runtime import LogicGraphRuntime
except ModuleNotFoundError:  # Standalone runtime generated by the exporter.
    from .controller_asset import AnimatorControllerRuntime
    from .logic_blackboard import BlackboardStore, load_blackboard_asset
    from .logic_event_bus import LogicEventBus
    from .logic_runtime import LogicGraphRuntime

Hydrator = Callable[[dict[str, dict[str, Any]], Path], list[tuple[str, str, str]]]


class ViewportRuntimeInitializer:
    """Build, incrementally extend and tear down a Play Mode runtime session."""

    def __init__(
        self,
        objects: dict[str, dict[str, Any]],
        logic_modules: dict[str, Any],
        logic_apis: dict[str, Any],
        animator_controllers: dict[str, Any],
        behavior_runners: dict[str, Any],
        logic_runtimes: dict[str, list[tuple[str, Any]]],
        initialized_ids: set[str],
        animator_event_signatures: dict[str, Any],
        runtime_world: Any,
        hydrators: tuple[Hydrator, ...],
        api_factory: Callable[[str, dict[str, Any]], Any],
        subgraph_loader: Callable[[str], dict[str, Any]],
        emit: Callable[[dict[str, Any]], None],
        play_audio: Callable[..., None],
        project_root: Path,
    ) -> None:
        self.objects = objects
        self.logic_modules = logic_modules
        self.logic_apis = logic_apis
        self.animator_controllers = animator_controllers
        self.behavior_runners = behavior_runners
        self.logic_runtimes = logic_runtimes
        self.initialized_ids = initialized_ids
        self.animator_event_signatures = animator_event_signatures
        self.runtime_world = runtime_world
        self.hydrators = hydrators
        self.api_factory = api_factory
        self.subgraph_loader = subgraph_loader
        self.emit = emit
        self.play_audio = play_audio
        self.project_root = project_root
        self.logic_blackboard = BlackboardStore()
        self.logic_event_bus = LogicEventBus()

    def start(self, scene_blackboard: dict[str, Any] | None = None) -> None:
        self._clear_runtime_state()
        self.runtime_world.reset_session()
        self._create_logic_services(scene_blackboard or {})
        initial_objects = list(self.objects.items())
        self._hydrate(self.objects)
        for name, obj in initial_objects:
            # BUG FIX: estas três chamadas não tinham try/except (diferente de
            # _initialize_logic, alguns linhas abaixo, que já é protegido).
            # Uma exceção em QUALQUER objeto (ex.: um Animator Controller mal
            # formado) propagava pra fora de start() inteiro, abortando a
            # inicialização de TODOS os objetos processados depois dele na
            # mesma lista — incluindo Logic Graphs de objetos completamente
            # não relacionados que nem chegavam a rodar. Isola cada chamada
            # por objeto e reporta no runtime_log em vez de derrubar tudo.
            for step, fn in (
                ("animação", self._initialize_animation),
                ("behavior tree", self._initialize_behavior),
                ("diálogo", self._initialize_dialogue),
            ):
                try:
                    fn(name, obj)
                except Exception as exc:
                    report_error(log, f"initialise {step} for object {name!r}", exc)
                    self.emit({
                        "type": "runtime_log", "level": "ERROR",
                        "message": f"{name}: falha ao inicializar {step}: {exc}",
                    })
        for name, obj in initial_objects:
            self._initialize_logic(name, obj)
        self.initialized_ids.update(str(obj.get("id", name)) for name, obj in initial_objects)
        self.start_spawned_objects()
        loaded = sum(len(entries) for entries in self.logic_runtimes.values())
        self.emit({
            "type": "runtime_log", "level": "INFO",
            "message": f"Play Mode carregou {loaded} Logic Graph(s); scripts Python estão desativados",
        })

    def stop(self, active_contacts: dict[Any, Any]) -> None:
        self._clear_runtime_state()
        active_contacts.clear()
        self.emit({"type": "logic_trace_clear"})

    def start_spawned_objects(self) -> None:
        active_names = set(self.objects)
        # Phase 5B.2: Cleanup physics handlers for removed objects
        for stale_name in set(self.logic_runtimes) - active_names:
            runtime_list = self.logic_runtimes.get(stale_name, [])
            for path, runtime in runtime_list:
                if hasattr(runtime, 'stop'):
                    with swallow(log, f"stop stale Logic Graph {path!r} for removed object {stale_name!r}",
                                 level=logging.WARNING):
                        runtime.stop()
            self.logic_runtimes.pop(stale_name, None)
            self.logic_apis.pop(stale_name, None)
            self.animator_controllers.pop(stale_name, None)
        pending = [
            (name, obj) for name, obj in list(self.objects.items())
            if str(obj.get("id", name)) not in self.initialized_ids
        ]
        for name, obj in pending:
            self.initialized_ids.add(str(obj.get("id", name)))
            self._hydrate({name: obj})
            for step, fn in (
                ("animação", self._initialize_animation),
                ("behavior tree", self._initialize_behavior),
                ("diálogo", self._initialize_dialogue),
            ):
                try:
                    fn(name, obj)
                except Exception as exc:
                    report_error(log, f"initialise {step} for spawned object {name!r}", exc)
                    self.emit({
                        "type": "runtime_log", "level": "ERROR",
                        "message": f"{name}: falha ao inicializar {step}: {exc}",
                    })
            self._initialize_logic(name, obj)
            audio = obj.get("audio")
            if isinstance(audio, dict) and audio.get("autoplay") and audio.get("path"):
                self.play_audio(
                    name, str(audio["path"]), float(audio.get("volume", 1.0)),
                    bool(audio.get("loop", False)),
                )

    def _clear_runtime_state(self) -> None:
        for name, runner in list(self.behavior_runners.items()):
            api = self.logic_apis.get(name)
            if api is not None:
                try:
                    runner.stop(api)
                except Exception as exc:
                    report_error(log, f"stop Behavior Tree for object {name!r}", exc,
                                 level=logging.WARNING)
                    self.emit({"type": "runtime_log", "level": "WARNING", "message": f"{name}: falha ao encerrar Behavior Tree: {exc}"})

        # Phase 5B.2: Cleanup physics event handlers on runtime stop
        for name, runtime_list in list(self.logic_runtimes.items()):
            for path, runtime in runtime_list:
                if hasattr(runtime, 'stop'):
                    # A failure here leaks physics/animation event handlers, so it
                    # must never be invisible (Phase 9.5A stability audit S4).
                    with swallow(log, f"stop Logic Graph {path!r} for object {name!r} during teardown",
                                 level=logging.WARNING):
                        runtime.stop()

        self.logic_runtimes.clear()
        self.logic_modules.clear()
        self.logic_apis.clear()
        self.animator_controllers.clear()
        self.behavior_runners.clear()
        self.initialized_ids.clear()
        self.animator_event_signatures.clear()

        # Phase 7B.7.3: Reset dialogue manager on Play/Stop
        with swallow(log, "reset the DialogueManager on Play/Stop", level=logging.WARNING):
            from engine.dialogue.manager import get_dialogue_manager
            manager = get_dialogue_manager()
            manager.reset()

    def _create_logic_services(self, scene_blackboard: dict[str, Any]) -> None:
        path = self.project_root / "Assets" / "Logic" / "ProjectBlackboard.zblackboard"
        try:
            project_blackboard = load_blackboard_asset(path) if path.is_file() else {}
        except (OSError, ValueError):
            project_blackboard = {}
        self.logic_blackboard = BlackboardStore(scene_blackboard, project_blackboard)
        self.logic_event_bus = LogicEventBus()
        # Phase 9.5B Stage 1: hand the live bus to the DialogueManager so
        # dialogue events actually reach Logic Graphs.  Previously it looked for
        # a LogicEventBus.get_instance() that does not exist.
        with swallow(log, "bind the LogicEventBus to the DialogueManager",
                     level=logging.WARNING):
            from engine.dialogue.manager import get_dialogue_manager
            get_dialogue_manager().bind_event_bus(self.logic_event_bus)

    def _hydrate(self, selected: dict[str, dict[str, Any]]) -> None:
        for hydrator in self.hydrators:
            for level, object_name, message in hydrator(selected, self.project_root):
                self.emit({
                    "type": "runtime_log", "level": level,
                    "message": f"{object_name}: {message}",
                })

    def _initialize_animation(self, name: str, obj: dict[str, Any]) -> None:
        animator = obj.get("animator")
        if not isinstance(animator, dict):
            return
        controller = animator.get("controller")
        if isinstance(controller, dict):
            runtime = AnimatorControllerRuntime(controller, animator.get("parameters", {}))
            self.animator_controllers[name] = runtime
            animator["parameters"] = dict(runtime.parameters)
            animator["active_clip"] = runtime.current_state
            obj["_animator_state"] = runtime.current_state
        obj["_current_animation_name"] = str(animator.get("active_clip", "Idle"))
        obj["_animation_time"], obj["_animation_frame"], obj["_animation_raw_frame"] = 0.0, 0, -1

    def _initialize_behavior(self, name: str, obj: dict[str, Any]) -> None:
        behavior = obj.get("behavior")
        if not isinstance(behavior, dict) or not bool(behavior.get("auto_start", True)):
            return
        api = self.logic_apis.setdefault(name, self.api_factory(name, obj))
        graph = behavior.get("graph")
        controller = behavior.get("controller")
        controller_path = str(behavior.get("controller_path", "")).strip()

        if controller_path:
            p = Path(controller_path)
            if not p.is_absolute():
                p = self.project_root / p
            if p.is_file():
                with swallow(log, f"load behavior controller asset {p}"):
                    import json
                    raw = json.loads(p.read_text(encoding="utf-8"))
                    if isinstance(raw, dict) and raw.get("format") == "zennity.generic_graph":
                        graph = raw
                        behavior["graph"] = raw

        if isinstance(graph, dict):
            runner = BehaviorGraphRunner(graph, self.project_root)
        elif isinstance(controller, dict):
            runner = BehaviorControllerRunner(
                controller, self.project_root, behavior.get("parameters", {})
            )
        else:
            return
        self.behavior_runners[name] = runner
        api.behavior.bind(runner, api)
        runner.start(api)
        obj["_behavior_state"] = runner.current_state

    def _initialize_dialogue(self, name: str, obj: dict[str, Any]) -> None:
        dialogue = obj.get("dialogue")
        if not isinstance(dialogue, dict) or not isinstance(dialogue.get("graph"), dict):
            return
        api = self.logic_apis.setdefault(name, self.api_factory(name, obj))
        session = DialogueSession(
            dialogue["graph"],
            dialogue.get("variables", {}),
            lambda event_name, payload: api.send(event_name, payload),
        )
        api.dialogue.bind(session)
        obj["_dialogue_session"] = session
        if dialogue.get("auto_start", False):
            api.dialogue.start()

    def _initialize_logic(self, name: str, obj: dict[str, Any]) -> None:
        entries = obj.get("logic_graphs", [])
        if not isinstance(entries, list):
            return
        for entry in entries:
            graph = entry.get("graph") if isinstance(entry, dict) else None
            if not isinstance(graph, dict):
                continue
            try:
                api = self.logic_apis.setdefault(name, self.api_factory(name, obj))
                runtime = LogicGraphRuntime(
                    graph, self.logic_blackboard, name, self.logic_event_bus,
                    self.subgraph_loader,
                )
                runtime.start(api)
                path = str(entry.get("path", graph.get("name", "Logic Graph")))
                self.logic_runtimes.setdefault(name, []).append((path, runtime))
            except Exception as exc:
                report_error(log, f"start Logic Graph for object {name!r}", exc)
                self.emit({
                    "type": "runtime_log", "level": "ERROR",
                    "message": f"{name}: Logic Graph: {exc}",
                })
