"""Shared visual definitions for the Logic Graph editor.

Keeping these values outside the editor facade prevents the mixins from importing
the concrete QWidget and forming a circular dependency.
"""

from PySide6.QtGui import QColor


CATEGORY_COLORS = {
    "Eventos": QColor("#d66ba0"),
    "Movimento": QColor("#4c9aff"),
    "Posição": QColor("#3fb6a8"),
    "Ação": QColor("#ae7df0"),
    "Lógica": QColor("#f0a64b"),
    "Condição": QColor("#50c878"),
    "Objetos": QColor("#47b8c8"),
    "Variáveis": QColor("#d5b84b"),
    "Subgrafos": QColor("#b48ead"),
    "Matemática": QColor("#e07a5f"),
    "Texto": QColor("#81b29a"),
    "Personalizado": QColor("#7f8b9c"),
}

PORT_COLORS = {
    "flow": QColor("#d9dde7"),
    "number": QColor("#58a6ff"),
    "bool": QColor("#50c878"),
    "text": QColor("#e6b85c"),
    "object": QColor("#47b8c8"),
    "movement": QColor("#ff8c69"),
    "any": QColor("#ae7df0"),
}

NODE_DESCRIPTIONS = {
    "event_collision_enter": "Executa quando este objeto começa uma colisão física.",
    "event_collision_exit": "Executa quando os objetos deixam de colidir.",
    "event_trigger_enter": "Executa ao entrar em um collider marcado como área/trigger.",
    "event_trigger_exit": "Executa ao sair de uma área/trigger.",
    "event_timer": "Espera a quantidade de segundos e pode repetir automaticamente.",
    "event_key_pressed": "Executa uma única vez no instante em que a tecla é apertada.",
    "event_object_created": "Executa quando este grafo cria uma instância; o novo objeto vira o alvo implícito.",
    "create_object": "Cria uma cópia profunda e independente; ações conectadas depois recebem automaticamente o novo objeto.",
    "get_tag": "Lê a Tag do objeto conectado, útil para identificar colisões e triggers.",
    "get_prefab_parameter": "Lê um valor exposto recebido quando esta instância do Prefab foi criada.",
    "create_prefab": "Cria um Prefab com overrides opcionais; câmera, áudio e lógica só são copiados quando autorizados.",
    "clone_object": "Duplica um objeto existente durante o Play Mode.",
    "destroy_after_time": "Agenda o descarte do alvo sem bloquear o restante do fluxo.",
    "add_component": "Adiciona e configura um componente no objeto alvo.",
    "remove_component": "Remove um componente opcional do objeto alvo.",
    "once": "Libera o fluxo somente na primeira execução.",
    "cooldown": "Libera o fluxo novamente após o intervalo configurado.",
    "restart_scene": "Restaura a cena ao estado capturado no início do Play Mode.",
    "get_position": "Lê as coordenadas X e Y atuais do objeto.",
    "move_by": "Move X e Y continuamente em unidades por segundo, sem exigir teclado.",
    "start_continuous_motion": "Inicia uma velocidade que continua ativa depois que a tecla é solta.",
    "update_continuous_motion": "Altera a velocidade desejada de um movimento já iniciado.",
    "pause_continuous_motion": "Pausa somente o movimento indicado, usando desaceleração quando configurada.",
    "resume_continuous_motion": "Continua um movimento pausado sem criar outro.",
    "stop_continuous_motion": "Interrompe o movimento indicado; identificador vazio mantém compatibilidade e para todos do alvo.",
    "get_continuous_motion": "Consulta velocidade, módulo e estado de um movimento durante o Play.",
    "key_pressed": "Verdadeiro somente no primeiro frame em que a tecla é apertada.",
    "key_held": "Verdadeiro durante todo o tempo em que a tecla fica segurada.",
    "compare_text": "Compara textos ignorando diferenças entre letras maiúsculas e minúsculas.",
    "patrol_axis": "Move entre dois limites e inverte automaticamente a direção ao alcançá-los.",
    "set_sprite": "Troca a imagem principal do objeto durante o Play Mode.",
    "start_texture_scroll": "Repete e desloca a imagem dentro do plano sem mover collider ou Transform.",
    "stop_texture_scroll": "Interrompe o deslocamento da imagem do plano.",
    "play_animation_asset": "Carrega e toca diretamente um arquivo de animação .zanim.",
    "stop_animation": "Interrompe a animação atual do objeto.",
    "set_position": "Move imediatamente o objeto para uma posição X e Y.",
    "rotate": "Acrescenta graus à rotação atual do objeto.",
    "set_active": "Mostra/ativa ou oculta/desativa o objeto.",
    "destroy_object": "Desativa o objeto durante o Play Mode.",
    "log_message": "Escreve uma mensagem no console do editor.",
    "add_number": "Soma dois números.",
    "subtract_number": "Subtrai B de A.",
    "multiply_number": "Multiplica dois números.",
    "divide_number": "Divide A por B e avisa se B for zero.",
    "absolute_number": "Remove o sinal negativo de um número.",
    "clamp_number": "Mantém o número entre um mínimo e um máximo.",
    "random_number": "Gera um número aleatório dentro do intervalo.",
    "delta_time": "Tempo transcorrido desde o último frame.",
    "join_text": "Junta dois valores em um único texto.",
    "to_text": "Converte número, booleano ou objeto em texto.",
}

PROPERTY_LABELS = {
    "seconds": "Segundos", "repeat": "Repetir", "minimum": "Mínimo", "maximum": "Máximo",
    "degrees": "Graus", "active": "Ativo", "text": "Texto", "value": "Valor",
    "default": "Valor inicial", "type": "Tipo", "name": "Nome", "path": "Arquivo",
    "speed": "Velocidade", "force": "Força", "condition": "Condição",
    "width": "Largura", "height": "Altura", "color": "Cor", "texture": "Imagem",
    "tag": "Tag", "relative": "Posição relativa", "inherit_source": "Copiar objeto original",
    "inherit_logic": "Copiar Logic Graphs também",
    "override_position": "Sobrescrever posição",
    "override_rotation": "Sobrescrever rotação",
    "override_scale": "Sobrescrever tamanho",
    "include_camera": "Copiar câmera do Prefab",
    "include_audio": "Copiar áudio do Prefab",
    "include_logic": "Copiar lógica do Prefab",
    "lifetime": "Destruir após (s, 0 = nunca)",
    "max_instances": "Máximo de instâncias (0 = ilimitado)",
    "max_distance": "Distância máxima (0 = ilimitada)",
    "use_pool": "Reutilizar por pool",
    "speed_x": "Velocidade X", "speed_y": "Velocidade Y",
    "repeat_x": "Repetir no eixo X", "repeat_y": "Repetir no eixo Y",
    "parallax": "Intensidade do parallax", "reset": "Voltar à origem",
    "send_to_background": "Enviar para camada Background",
    "movement": "Identificador do movimento",
    "space": "Espaço (global/local)",
    "acceleration": "Aceleração",
    "deceleration": "Desaceleração",
    "smooth": "Parada suave",
}

NODE_PROPERTY_LABELS = {
    "move_by": {"x": "Velocidade X", "y": "Velocidade Y"},
    "start_continuous_motion": {"x": "Velocidade permanente X", "y": "Velocidade permanente Y"},
    "update_continuous_motion": {"x": "Nova velocidade X", "y": "Nova velocidade Y"},
    "set_position": {"x": "Posição X", "y": "Posição Y"},
    "patrol_axis": {"axis": "Eixo", "minimum": "Limite mínimo", "maximum": "Limite máximo", "speed": "Velocidade"},
    "create_object": {"x": "Posição X", "y": "Posição Y"},
    "create_prefab": {
        "x": "Posição X", "y": "Posição Y", "rotation": "Rotação",
        "width": "Largura", "height": "Altura",
    },
}
