"""UI composition for the visual Logic Graph workspace."""
from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QCheckBox, QComboBox, QFrame, QGraphicsScene, QHBoxLayout, QLabel,
    QLineEdit, QListWidget, QPushButton, QSplitter, QTabWidget, QToolButton,
    QTreeWidget, QVBoxLayout, QWidget,
)

from editor.ui.icons import editor_icon
from engine.i18n import tr

from .views import LogicGraphView, LogicMiniMapView


def build_logic_graph_ui(self) -> None:
    root = QVBoxLayout(self)
    root.setContentsMargins(8, 8, 8, 8)
    root.setSpacing(8)

    title_row = QHBoxLayout()
    title = QLabel("Editor de Lógica Visual")
    title.setObjectName("WorkspaceTitle")
    self.asset_label = QLabel("Novo Logic Graph — ainda não salvo")
    self.asset_label.setObjectName("WorkspaceStatus")
    self.validation_label = QLabel("Grafo vazio")
    self.validation_label.setObjectName("WorkspaceContext")
    title_row.addWidget(title)
    title_row.addWidget(self.asset_label)
    title_row.addStretch(1)
    title_row.addWidget(self.validation_label)
    self.debug_status_label = QLabel("● DEBUG INATIVO")
    self.debug_status_label.setObjectName("WorkspaceContext")
    title_row.addWidget(self.debug_status_label)
    root.addLayout(title_row)

    toolbar_widget = QWidget()
    toolbar_widget.setObjectName("LogicToolbar")
    toolbar = QHBoxLayout(toolbar_widget)
    toolbar.setContentsMargins(6, 4, 6, 4)
    toolbar.setSpacing(4)
    self.new_button = QToolButton()
    self.open_button = QToolButton()
    self.save_button = QToolButton()
    self.save_as_button = QToolButton()
    for button, icon_name, tooltip in (
        (self.new_button, "new", "Novo Logic Graph"),
        (self.open_button, "open", "Abrir Logic Graph"),
        (self.save_button, "save", "Salvar"),
        (self.save_as_button, "save", "Salvar como..."),
    ):
        button.setIcon(editor_icon(icon_name))
        button.setToolTip(tooltip)
        button.setProperty("uiRole", "icon")
        toolbar.addWidget(button)
    toolbar.addSpacing(8)
    self.new_subgraph_button = QPushButton("Novo subgrafo")
    self.new_subgraph_button.setToolTip("Cria uma função visual reutilizável com entrada e retorno")
    toolbar.addWidget(self.new_subgraph_button)
    self.demo_button = QPushButton("Abrir exemplo...")
    self.demo_button.setIcon(editor_icon("open"))
    self.demo_button.setProperty("uiRole", "primary")
    self.demo_button.setToolTip("Escolha e abra um exemplo salvo de Logic Graph")
    toolbar.addWidget(self.demo_button)
    toolbar.addSpacing(8)
    self.play_button = QPushButton("Play")
    self.play_button.setIcon(editor_icon("play"))
    self.play_button.setProperty("uiRole", "primary")
    self.play_button.setToolTip("Salva o grafo atual e inicia o Play Mode")
    self.stop_button = QPushButton("Stop")
    self.stop_button.setIcon(editor_icon("stop"))
    self.stop_button.setProperty("uiRole", "danger")
    self.stop_button.setToolTip("Interrompe o Play Mode e restaura a cena")
    self.stop_button.setEnabled(False)
    toolbar.addWidget(self.play_button)
    toolbar.addWidget(self.stop_button)
    toolbar.addSpacing(12)
    self.graph_enabled_check = QCheckBox("Ativo no Play")
    self.graph_enabled_check.setChecked(True)
    self.graph_enabled_check.setToolTip("Desative para preservar o asset sem executá-lo")
    toolbar.addWidget(self.graph_enabled_check)
    toolbar.addWidget(QLabel("OBJETO ALVO"))
    self.target_type = QComboBox()
    self.target_type.addItem("Nome", "name")
    self.target_type.addItem("Tag", "tag")
    self.target_type.setMaximumWidth(82)
    self.target_value = QLineEdit("Player")
    self.target_value.setPlaceholderText("Player")
    self.target_value.setMaximumWidth(150)
    toolbar.addWidget(self.target_type)
    toolbar.addWidget(self.target_value)
    self.help_button = QPushButton("Ajuda")
    self.help_button.setToolTip(tr("editor.help.tooltip", "Dicionário de nós e documentação"))
    self.help_button.clicked.connect(lambda: right_tabs.setCurrentWidget(self.help_dock))
    toolbar.addWidget(self.help_button)
    toolbar.addStretch(1)
    self.fit_button = QPushButton("Enquadrar")
    self.undo_button = QPushButton("Desfazer")
    self.redo_button = QPushButton("Refazer")
    self.undo_button.setShortcut("Ctrl+Z")
    self.redo_button.setShortcut("Ctrl+Y")
    self.undo_button.setEnabled(False)
    self.redo_button.setEnabled(False)
    self.breakpoint_button = QPushButton("● Breakpoint")
    self.breakpoint_button.setToolTip("Alterna um breakpoint no nó selecionado (duplo clique também funciona)")
    self.continue_debug_button = QPushButton("Continuar")
    self.step_debug_button = QPushButton("Próximo nó")
    self.restart_debug_button = QPushButton("Reiniciar")
    self.continue_debug_button.setEnabled(False)
    self.step_debug_button.setEnabled(False)
    self.restart_debug_button.setEnabled(False)
    self.connect_button = QPushButton("Conectar selecionados")
    self.delete_button = QPushButton("Excluir selecionado")
    self.delete_button.setProperty("uiRole", "danger")
    toolbar.addWidget(self.fit_button)
    toolbar.addWidget(self.undo_button)
    toolbar.addWidget(self.redo_button)
    toolbar.addWidget(self.breakpoint_button)
    toolbar.addWidget(self.continue_debug_button)
    toolbar.addWidget(self.step_debug_button)
    toolbar.addWidget(self.restart_debug_button)
    toolbar.addWidget(self.connect_button)
    toolbar.addWidget(self.delete_button)
    root.addWidget(toolbar_widget)

    category_widget = QWidget()
    category_widget.setObjectName("LogicCategories")
    categories = QHBoxLayout(category_widget)
    categories.setContentsMargins(4, 4, 4, 4)
    categories.setSpacing(6)
    categories.addWidget(QLabel("Categoria"))
    self.category_combo = QComboBox()
    self.category_combo.addItem(tr("graph.categories.movement", "Movimento"), "Movement")
    self.category_combo.addItem(tr("graph.categories.position", "Posição"), "Position")
    self.category_combo.addItem(tr("graph.categories.action", "Ação"), "Action")
    self.category_combo.addItem(tr("graph.categories.logic", "Lógica"), "Logic")
    self.category_combo.addItem(tr("graph.categories.condition", "Condição"), "Condition")
    self.category_combo.addItem(tr("graph.categories.events", "Eventos"), "Events")
    self.category_combo.addItem(tr("graph.categories.objects", "Objetos"), "Objects")
    self.category_combo.addItem(tr("graph.categories.variables", "Variáveis"), "Variables")
    self.category_combo.addItem(tr("graph.categories.math", "Matemática"), "Math")
    self.category_combo.addItem(tr("graph.categories.text", "Texto"), "Text")
    self.category_combo.addItem(tr("graph.categories.subgraphs", "Subgrafos"), "Subgraphs")
    self.category_combo.addItem(tr("graph.categories.all", "Todos"), "All")
    self.category_combo.setMinimumWidth(150)
    self.category_combo.setToolTip("Filtra a biblioteca de blocos por categoria")
    categories.addWidget(self.category_combo)
    self.add_group_button = QPushButton("+ Grupo")
    self.add_comment_button = QPushButton("+ Comentário")
    self.organize_button = QPushButton("Organizar grafo")
    self.align_button = QPushButton("Alinhar")
    self.distribute_button = QPushButton("Distribuir")
    categories.addWidget(self.add_group_button)
    categories.addWidget(self.add_comment_button)
    categories.addWidget(self.organize_button)
    categories.addWidget(self.align_button)
    categories.addWidget(self.distribute_button)
    categories.addStretch(1)
    root.addWidget(category_widget)

    splitter = QSplitter(Qt.Horizontal)
    splitter.setObjectName("LogicContentSplitter")
    splitter.setChildrenCollapsible(False)

    palette_panel = QFrame()
    palette_panel.setObjectName("LogicPalettePanel")
    palette_layout = QVBoxLayout(palette_panel)
    palette_layout.setContentsMargins(8, 8, 8, 8)
    self.library_tabs = QTabWidget()
    self.library_tabs.setObjectName("LogicLibraryTabs")
    palette_layout.addWidget(self.library_tabs, 1)

    blocks_page = QWidget()
    blocks_layout = QVBoxLayout(blocks_page)
    blocks_layout.setContentsMargins(5, 6, 5, 6)
    blocks_layout.setSpacing(6)
    self.node_search = QLineEdit()
    self.node_search.setPlaceholderText("Pesquisar blocos...  ex.: colisão, som, somar")
    self.node_search.setClearButtonEnabled(True)
    blocks_layout.addWidget(self.node_search)
    self.palette = QListWidget()
    self.palette.setObjectName("LogicNodePalette")
    self.palette.setToolTip("Duplo clique para adicionar um nó")
    blocks_layout.addWidget(self.palette, 1)
    self.palette_count = QLabel()
    self.palette_count.setObjectName("PanelHint")
    blocks_layout.addWidget(self.palette_count)
    blocks_hint = QLabel("Duplo clique adiciona o bloco. Arraste uma porta para conectar.")
    blocks_hint.setObjectName("PanelHint")
    blocks_hint.setWordWrap(True)
    blocks_layout.addWidget(blocks_hint)
    self.library_tabs.addTab(blocks_page, "Blocos")

    recipes_page = QWidget()
    recipes_layout = QVBoxLayout(recipes_page)
    recipes_layout.setContentsMargins(5, 6, 5, 6)
    recipes_layout.setSpacing(6)
    self.recipe_topic_label = QLabel("Receitas de Movimento")
    self.recipe_topic_label.setObjectName("PanelSectionTitle")
    recipes_layout.addWidget(self.recipe_topic_label)
    self.recipe_search = QLineEdit()
    self.recipe_search.setPlaceholderText("O que você quer fazer? ex.: mover sozinho")
    self.recipe_search.setClearButtonEnabled(True)
    recipes_layout.addWidget(self.recipe_search)
    self.recipe_list = QListWidget()
    self.recipe_list.setToolTip("Escolha uma lógica pronta para aprender e inserir")
    recipes_layout.addWidget(self.recipe_list, 1)
    self.recipe_summary = QLabel("Escolha uma receita para ver como ela funciona.")
    self.recipe_summary.setObjectName("PanelHint")
    self.recipe_summary.setWordWrap(True)
    recipes_layout.addWidget(self.recipe_summary)
    self.recipe_apply_button = QPushButton("Inserir receita no grafo")
    self.recipe_apply_button.setProperty("uiRole", "primary")
    self.recipe_apply_button.setEnabled(False)
    recipes_layout.addWidget(self.recipe_apply_button)
    self.library_tabs.addTab(recipes_page, "Receitas")

    subgraphs_page = QWidget()
    subgraphs_layout = QVBoxLayout(subgraphs_page)
    subgraphs_layout.setContentsMargins(5, 6, 5, 6)
    subgraphs_layout.setSpacing(6)
    self.subgraph_list = QListWidget()
    self.subgraph_list.setToolTip("Duplo clique adiciona uma chamada ao subgrafo")
    subgraphs_layout.addWidget(self.subgraph_list, 1)
    subgraph_hint = QLabel("Funções visuais reutilizáveis salvas em Assets/Logic.")
    subgraph_hint.setObjectName("PanelHint")
    subgraph_hint.setWordWrap(True)
    subgraphs_layout.addWidget(subgraph_hint)
    self.library_tabs.addTab(subgraphs_page, "Subgrafos")

    data_page = QWidget()
    data_layout = QVBoxLayout(data_page)
    data_layout.setContentsMargins(5, 6, 5, 6)
    data_layout.setSpacing(6)
    self.blackboard_tree = QTreeWidget()
    self.blackboard_tree.setHeaderLabels(["Nome", "Tipo", "Escopo"])
    data_layout.addWidget(self.blackboard_tree, 1)
    self.blackboard_name_edit = QLineEdit()
    self.blackboard_name_edit.setPlaceholderText("nome_da_variável")
    data_layout.addWidget(self.blackboard_name_edit)
    blackboard_options = QHBoxLayout()
    self.blackboard_type_combo = QComboBox()
    for label, value in (("Número", "number"), ("Booleano", "bool"), ("Texto", "text"), ("Objeto", "object")):
        self.blackboard_type_combo.addItem(label, value)
    self.blackboard_scope_combo = QComboBox()
    for label, value in (("Objeto", "object"), ("Cena", "scene"), ("Projeto", "project")):
        self.blackboard_scope_combo.addItem(label, value)
    blackboard_options.addWidget(self.blackboard_type_combo)
    blackboard_options.addWidget(self.blackboard_scope_combo)
    data_layout.addLayout(blackboard_options)
    self.blackboard_default_edit = QLineEdit("0")
    self.blackboard_default_edit.setPlaceholderText("Valor inicial")
    data_layout.addWidget(self.blackboard_default_edit)
    blackboard_edit_actions = QHBoxLayout()
    self.blackboard_save_button = QPushButton("Adicionar")
    self.blackboard_remove_button = QPushButton("Excluir")
    blackboard_edit_actions.addWidget(self.blackboard_save_button)
    blackboard_edit_actions.addWidget(self.blackboard_remove_button)
    data_layout.addLayout(blackboard_edit_actions)
    blackboard_node_actions = QHBoxLayout()
    self.blackboard_get_button = QPushButton("Ler")
    self.blackboard_set_button = QPushButton("Definir")
    blackboard_node_actions.addWidget(self.blackboard_get_button)
    blackboard_node_actions.addWidget(self.blackboard_set_button)
    data_layout.addLayout(blackboard_node_actions)
    data_hint = QLabel("Variáveis organizadas por objeto, cena ou projeto.")
    data_hint.setObjectName("PanelHint")
    data_hint.setWordWrap(True)
    data_layout.addWidget(data_hint)
    self.library_tabs.addTab(data_page, "Dados")
    palette_panel.setMinimumWidth(230)
    splitter.addWidget(palette_panel)

    self.scene = QGraphicsScene(self)
    self.scene.setSceneRect(-2000.0, -1400.0, 4000.0, 2800.0)
    canvas_splitter = QSplitter(Qt.Vertical)
    canvas_splitter.setChildrenCollapsible(False)
    
    canvas_panel = QWidget()
    canvas_layout = QVBoxLayout(canvas_panel)
    canvas_layout.setContentsMargins(0, 0, 0, 0)
    canvas_layout.setSpacing(3)
    self.view = LogicGraphView(self.scene, self)
    canvas_layout.addWidget(self.view, 1)
    minimap_row = QHBoxLayout()
    minimap_row.addStretch(1)
    self.minimap = LogicMiniMapView(self.scene, self)
    minimap_row.addWidget(self.minimap)
    canvas_layout.addLayout(minimap_row)
    canvas_splitter.addWidget(canvas_panel)
    
    from editor.widgets.phase1_viewport import Phase1ViewportWidget
    self.mini_viewport = Phase1ViewportWidget()
    canvas_splitter.addWidget(self.mini_viewport)
    
    splitter.addWidget(canvas_splitter)

    right_tabs = QTabWidget()
    right_tabs.setObjectName("LogicRightTabs")
    
    properties_panel = QFrame()
    properties_panel.setObjectName("LogicPropertiesPanel")
    properties_layout = QVBoxLayout(properties_panel)
    properties_layout.setContentsMargins(8, 8, 8, 8)
    properties_title = QLabel("PROPRIEDADES DO NÓ")
    properties_title.setObjectName("PanelSectionTitle")
    properties_layout.addWidget(properties_title)
    self.selected_label = QLabel("Nenhum nó selecionado")
    self.selected_label.setObjectName("WorkspaceContext")
    self.selected_label.setWordWrap(True)
    properties_layout.addWidget(self.selected_label)
    self.property_tree = QTreeWidget()
    self.property_tree.setObjectName("LogicPropertyTree")
    self.property_tree.setHeaderLabels(["Propriedade", "Valor"])
    self.property_tree.setColumnWidth(0, 105)
    properties_layout.addWidget(self.property_tree, 1)
    self.property_asset_button = QPushButton("Selecionar asset do projeto...")
    self.property_asset_button.setToolTip("Vincula uma imagem, animação ou som da pasta Assets")
    self.property_asset_button.hide()
    properties_layout.addWidget(self.property_asset_button)
    self.breakpoint_condition_label = QLabel("CONDIÇÃO DO BREAKPOINT")
    self.breakpoint_condition_label.setObjectName("PanelSectionTitle")
    properties_layout.addWidget(self.breakpoint_condition_label)
    self.breakpoint_condition_edit = QLineEdit()
    self.breakpoint_condition_edit.setPlaceholderText("Ex.: vida <= 0 ou estado == andando")
    self.breakpoint_condition_edit.setEnabled(False)
    properties_layout.addWidget(self.breakpoint_condition_edit)
    self.runtime_values_title = QLabel("VALORES EM EXECUÇÃO")
    self.runtime_values_title.setObjectName("PanelSectionTitle")
    self.runtime_values_title.hide()
    properties_layout.addWidget(self.runtime_values_title)
    self.runtime_values_tree = QTreeWidget()
    self.runtime_values_tree.setHeaderLabels(["Nó / variável", "Valor"])
    self.runtime_values_tree.setMaximumHeight(155)
    self.runtime_values_tree.hide()
    properties_layout.addWidget(self.runtime_values_tree)
    watch_title = QLabel("OBSERVADORES")
    watch_title.setObjectName("PanelSectionTitle")
    properties_layout.addWidget(watch_title)
    self.watch_values_tree = QTreeWidget()
    self.watch_values_tree.setHeaderLabels(["Expressão", "Valor"])
    self.watch_values_tree.setMaximumHeight(135)
    properties_layout.addWidget(self.watch_values_tree)
    watch_row = QHBoxLayout()
    self.watch_expression_edit = QLineEdit()
    self.watch_expression_edit.setPlaceholderText("vida, x, grounded...")
    self.add_watch_button = QPushButton("+")
    self.add_watch_button.setToolTip("Adicionar observador")
    self.remove_watch_button = QPushButton("−")
    self.remove_watch_button.setToolTip("Remover observador selecionado")
    watch_row.addWidget(self.watch_expression_edit, 1)
    watch_row.addWidget(self.add_watch_button)
    watch_row.addWidget(self.remove_watch_button)
    properties_layout.addLayout(watch_row)
    property_hint = QLabel(
        "Delete remove, Ctrl+D duplica e Esc cancela uma conexão. "
        "Use −/+ no bloco para recolher e a alça inferior para redimensionar."
    )
    property_hint.setObjectName("PanelHint")
    property_hint.setWordWrap(True)
    properties_layout.addWidget(property_hint)
    properties_panel.setMinimumWidth(230)
    right_tabs.addTab(properties_panel, tr("editor.tabs.properties", "Propriedades"))
    
    from .help_dock import LogicHelpDock
    self.help_dock = LogicHelpDock()
    right_tabs.addTab(self.help_dock, tr("editor.tabs.help", "Ajuda"))
    
    splitter.addWidget(right_tabs)
    splitter.setStretchFactor(0, 0)
    splitter.setStretchFactor(1, 1)
    splitter.setStretchFactor(2, 0)
    splitter.setSizes([190, 700, 240])
    root.addWidget(splitter, 1)
    self._refresh_palette("Movimento")
    self._refresh_recipes("")

