"""Declarative definitions of all native visual logic nodes in the Zennity Engine."""

from __future__ import annotations

from typing import Any

NODE_DEFINITIONS: dict[str, dict[str, Any]] = {
    "absolute_number": {
        "title": "Absolute Number",
        "category": "Math",
        "inputs": [('value', 'number')],
        "outputs": [('value', 'number')],
        "properties": {"value": 0.0},
    },
    "add_component": {
        "title": "Add Component",
        "category": "Math",
        "inputs": [('in', 'flow'), ('target', 'object')],
        "outputs": [('next', 'flow')],
        "properties": {"component_type": ""},
    },
    "add_number": {
        "title": "Add Number",
        "category": "Math",
        "inputs": [('a', 'number'), ('b', 'number')],
        "outputs": [('value', 'number')],
        "properties": {"a": 0.0, "b": 0.0},
    },
    "and": {
        "title": "And",
        "category": "Logic",
        "inputs": [('a', 'bool'), ('b', 'bool')],
        "outputs": [('value', 'bool')],
        "properties": {"a": False, "b": False},
    },
    "bool_value": {
        "title": "Bool Value",
        "category": "Action",
        "inputs": [],
        "outputs": [('value', 'bool')],
        "properties": {"value": True},
    },
    "call_subgraph": {
        "title": "Call Subgraph",
        "category": "Subgraphs",
        "inputs": [('in', 'flow')],
        "outputs": [('next', 'flow')],
        "properties": {"subgraph_path": ""},
    },
    "clamp_number": {
        "title": "Clamp Number",
        "category": "Math",
        "inputs": [('value', 'number'), ('minimum', 'number'), ('maximum', 'number')],
        "outputs": [('value', 'number')],
        "properties": {"value": 0.0, "minimum": 0.0, "maximum": 1.0},
    },
    "clone_object": {
        "title": "Clone Object",
        "category": "Spawning",
        "inputs": [('in', 'flow'), ('target', 'object'), ('name', 'text')],
        "outputs": [('next', 'flow'), ('limit_reached', 'flow'), ('object', 'object')],
        "properties": {"target": "", "name": "ClonedObject"},
    },
    "compare_number": {
        "title": "Compare Number",
        "category": "Logic",
        "inputs": [('in', 'flow'), ('value', 'number')],
        "outputs": [('true', 'flow'), ('false', 'flow'), ('value', 'bool')],
        "properties": {"operator": ">", "value": 0.0},
    },
    "compare_text": {
        "title": "Compare Text",
        "category": "Logic",
        "inputs": [('in', 'flow'), ('value', 'text')],
        "outputs": [('true', 'flow'), ('false', 'flow'), ('value', 'bool')],
        "properties": {"operator": "==", "value": ""},
    },
    "cooldown": {
        "title": "Cooldown",
        "category": "Logic",
        "inputs": [('in', 'flow'), ('seconds', 'number')],
        "outputs": [('next', 'flow'), ('blocked', 'flow')],
        "properties": {"seconds": 1.0},
    },
    "create_object": {
        "title": "Create Object",
        "category": "Spawning",
        "inputs": [('in', 'flow'), ('source', 'object'), ('name', 'text'), ('x', 'number'), ('y', 'number')],
        "outputs": [('next', 'flow'), ('limit_reached', 'flow'), ('object', 'object')],
        "properties": {"name": "NovoObjeto", "x": 0.0, "y": 0.0},
    },
    "create_prefab": {
        "title": "Create Prefab",
        "category": "Spawning",
        "inputs": [('in', 'flow'), ('x', 'number'), ('y', 'number'), ('rotation', 'number'), ('width', 'number'), ('height', 'number')],
        "outputs": [('next', 'flow'), ('limit_reached', 'flow'), ('object', 'object')],
        "properties": {"prefab_path": "", "x": 0.0, "y": 0.0, "rotation": 0.0},
    },
    "delta_time": {
        "title": "Delta Time",
        "category": "Math",
        "inputs": [],
        "outputs": [('value', 'number')],
        "properties": {},
    },
    "destroy_after_time": {
        "title": "Destroy After Time",
        "category": "Action",
        "inputs": [('in', 'flow'), ('target', 'object'), ('seconds', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "seconds": 1.0},
    },
    "destroy_object": {
        "title": "Destroy Object",
        "category": "Action",
        "inputs": [('in', 'flow'), ('target', 'object')],
        "outputs": [],
        "properties": {"target": ""},
    },
    "start_behavior_tree": {
        "title": "Start Behavior Tree",
        "category": "Action",
        "inputs": [('in', 'flow'), ('target', 'object'), ('path', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "path": ""},
    },
    "divide_number": {
        "title": "Divide Number",
        "category": "Math",
        "inputs": [('a', 'number'), ('b', 'number')],
        "outputs": [('value', 'number')],
        "properties": {"a": 0.0, "b": 1.0},
    },
    "emit_event": {
        "title": "Emit Event",
        "category": "Events",
        "inputs": [('in', 'flow'), ('payload', 'any')],
        "outputs": [('next', 'flow')],
        "properties": {"event_name": "MyEvent"},
    },
    "event_collision_enter": {
        "title": "Event Collision Enter",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('other', 'object')],
        "properties": {},
    },
    "event_collision_exit": {
        "title": "Event Collision Exit",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('other', 'object')],
        "properties": {},
    },
    "event_created": {
        "title": "Event Created",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('created_object', 'object')],
        "properties": {},
    },
    "event_custom": {
        "title": "Event Custom",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('payload', 'any')],
        "properties": {"event_name": "MyEvent"},
    },
    "event_key_pressed": {
        "title": "Event Key Pressed",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow')],
        "properties": {"key": "SPACE"},
    },
    "event_object_created": {
        "title": "Event Object Created",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('object', 'object')],
        "properties": {},
    },
    "event_spawn_limit_reached": {
        "title": "Event Spawn Limit Reached",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "event_start": {
        "title": "Event Start",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "event_timer": {
        "title": "Event Timer",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow')],
        "properties": {"seconds": 1.0},
    },
    "event_trigger_enter": {
        "title": "Event Trigger Enter",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('other', 'object')],
        "properties": {},
    },
    "event_trigger_exit": {
        "title": "Event Trigger Exit",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('other', 'object')],
        "properties": {},
    },
    "event_update": {
        "title": "Event Update",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "find_tag": {
        "title": "Find Tag",
        "category": "Objects",
        "inputs": [('in', 'flow')],
        "outputs": [('next', 'flow'), ('object', 'object')],
        "properties": {"tag": "Player"},
    },
    "get_continuous_motion": {
        "title": "Get Continuous Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('movement', 'movement')],
        "outputs": [('next', 'flow'), ('x', 'number'), ('y', 'number'), ('speed', 'number'), ('paused', 'bool'), ('active', 'bool')],
        "properties": {"target": ""},
    },
    "get_position": {
        "title": "Get Position",
        "category": "Position",
        "inputs": [('target', 'object')],
        "outputs": [('x', 'number'), ('y', 'number')],
        "properties": {"target": ""},
    },
    "get_position_x": {
        "title": "Get Position X",
        "category": "Position",
        "inputs": [('target', 'object')],
        "outputs": [('value', 'number')],
        "properties": {"target": ""},
    },
    "get_position_y": {
        "title": "Get Position Y",
        "category": "Position",
        "inputs": [('target', 'object')],
        "outputs": [('value', 'number')],
        "properties": {"target": ""},
    },
    "get_prefab_parameter": {
        "title": "Get Prefab Parameter",
        "category": "Action",
        "inputs": [('target', 'object')],
        "outputs": [('value', 'any')],
        "properties": {"parameter": "param_name"},
    },
    "get_tag": {
        "title": "Get Tag",
        "category": "Objects",
        "inputs": [('target', 'object')],
        "outputs": [('value', 'text')],
        "properties": {"target": "", "tag": "Player"},
    },
    "get_variable": {
        "title": "Get Variable",
        "category": "Variables",
        "inputs": [('in', 'flow')],
        "outputs": [('next', 'flow'), ('value', 'any')],
        "properties": {"name": "var_name"},
    },
    "if_else": {
        "title": "If Else",
        "category": "Logic",
        "inputs": [('in', 'flow'), ('condition', 'bool')],
        "outputs": [('true', 'flow'), ('false', 'flow')],
        "properties": {"condition": False},
    },
    "input_axis": {
        "title": "Read Key Axis",
        "category": "Input",
        "inputs": [('in', 'flow')],
        "outputs": [('next', 'flow'), ('value', 'number')],
        "properties": {"negative": "A", "positive": "D"},
    },
    "is_grounded": {
        "title": "Is Grounded",
        "category": "Action",
        "inputs": [('in', 'flow')],
        "outputs": [('true', 'flow'), ('false', 'flow'), ('value', 'bool')],
        "properties": {},
    },
    "join_text": {
        "title": "Join Text",
        "category": "Text",
        "inputs": [('a', 'any'), ('b', 'any')],
        "outputs": [('value', 'text')],
        "properties": {"a": "", "b": ""},
    },
    "jump": {
        "title": "Jump",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('force', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"force": 300.0},
    },
    "key_held": {
        "title": "Key Held",
        "category": "Input",
        "inputs": [('in', 'flow')],
        "outputs": [('true', 'flow'), ('false', 'flow'), ('value', 'bool')],
        "properties": {"key": "SPACE"},
    },
    "key_pressed": {
        "title": "Key Pressed",
        "category": "Input",
        "inputs": [('in', 'flow')],
        "outputs": [('true', 'flow'), ('false', 'flow'), ('value', 'bool')],
        "properties": {"key": "SPACE"},
    },
    "log_message": {
        "title": "Log Message",
        "category": "Action",
        "inputs": [('in', 'flow'), ('text', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"text": "Log message"},
    },
    "motion_state_query": {
        "title": "Motion State Query",
        "category": "Movement",
        "inputs": [('handle', 'movement')],
        "outputs": [('active', 'bool'), ('current_speed', 'number')],
        "properties": {},
    },
    "move": {
        "title": "Move",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('value', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"speed": 200.0},
    },
    "move_by": {
        "title": "Move By",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('x', 'number'), ('y', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "x": 100.0, "y": 0.0},
    },
    "move_towards": {
        "title": "Move Towards",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('speed', 'number'), ('destination_x', 'number'), ('destination_y', 'number'), ('target', 'object')],
        "outputs": [('next', 'flow'), ('handle', 'movement')],
        "properties": {"target": "", "speed": 100.0, "destination_x": 0.0, "destination_y": 0.0},
    },
    "move_x": {
        "title": "Move X",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('speed', 'number'), ('target', 'object')],
        "outputs": [('next', 'flow'), ('handle', 'movement')],
        "properties": {"target": "", "speed": 100.0},
    },
    "move_y": {
        "title": "Move Y",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('speed', 'number'), ('target', 'object')],
        "outputs": [('next', 'flow'), ('handle', 'movement')],
        "properties": {"target": "", "speed": 100.0},
    },
    "multiply_number": {
        "title": "Multiply Number",
        "category": "Math",
        "inputs": [('a', 'number'), ('b', 'number')],
        "outputs": [('value', 'number')],
        "properties": {"a": 1.0, "b": 1.0},
    },
    "not": {
        "title": "Not",
        "category": "Logic",
        "inputs": [('value', 'bool')],
        "outputs": [('value', 'bool')],
        "properties": {"value": False},
    },
    "number_value": {
        "title": "Number Value",
        "category": "Math",
        "inputs": [],
        "outputs": [('value', 'number')],
        "properties": {"value": 0.0},
    },
    "once": {
        "title": "Once",
        "category": "Logic",
        "inputs": [('in', 'flow')],
        "outputs": [('next', 'flow'), ('blocked', 'flow')],
        "properties": {},
    },
    "or": {
        "title": "Or",
        "category": "Logic",
        "inputs": [('a', 'bool'), ('b', 'bool')],
        "outputs": [('value', 'bool')],
        "properties": {"a": False, "b": False},
    },
    "patrol_axis": {
        "title": "Patrol Axis",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('minimum', 'number'), ('maximum', 'number'), ('speed', 'number')],
        "outputs": [('next', 'flow'), ('direction', 'number'), ('position', 'number')],
        "properties": {"target": "", "minimum": -100.0, "maximum": 100.0, "speed": 100.0},
    },
    "pause_continuous_motion": {
        "title": "Pause Continuous Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('movement', 'movement')],
        "outputs": [('next', 'flow')],
        "properties": {"target": ""},
    },
    "pause_motion": {
        "title": "Pause Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('handle', 'movement')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "play_animation": {
        "title": "Play Animation",
        "category": "Animation",
        "inputs": [('in', 'flow'), ('target', 'object'), ('state', 'text')],
        "outputs": [('next', 'flow'), ('exec_failure', 'flow')],
        "properties": {"target": "", "state": "Idle", "force": False},
    },
    "play_animation_asset": {
        "title": "Play Animation Asset",
        "category": "Animation",
        "inputs": [('in', 'flow'), ('path', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"path": ""},
    },
    "play_sound": {
        "title": "Play Sound",
        "category": "Audio",
        "inputs": [('in', 'flow'), ('path', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"path": ""},
    },
    "set_ui_text": {
        "title": "Atualizar texto da UI", "category": "UI",
        "inputs": [('in', 'flow'), ('text', 'text')], "outputs": [('next', 'flow')],
        "properties": {"object": "", "text": ""},
    },
    "set_ui_progress_bar": {
        "title": "Atualizar barra da UI", "category": "UI",
        "inputs": [('in', 'flow'), ('value', 'number')], "outputs": [('next', 'flow')],
        "properties": {"object": "", "value": 100.0, "max_value": 100.0},
    },
    "random_number": {
        "title": "Random Number",
        "category": "Logic",
        "inputs": [('minimum', 'number'), ('maximum', 'number')],
        "outputs": [('value', 'number')],
        "properties": {"minimum": 0.0, "maximum": 1.0},
    },
    "remove_component": {
        "title": "Remove Component",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "component_type": ""},
    },
    "restart_scene": {
        "title": "Restart Scene",
        "category": "Action",
        "inputs": [('in', 'flow')],
        "outputs": [],
        "properties": {},
    },
    "resume_continuous_motion": {
        "title": "Resume Continuous Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('movement', 'movement')],
        "outputs": [('next', 'flow')],
        "properties": {"target": ""},
    },
    "resume_motion": {
        "title": "Resume Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('handle', 'movement')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "rotate": {
        "title": "Rotate",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('degrees', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "degrees": 90.0},
    },
    "self_object": {
        "title": "Self Object",
        "category": "Objects",
        "inputs": [],
        "outputs": [('object', 'object')],
        "properties": {},
    },
    "sequence": {
        "title": "Sequence",
        "category": "Logic",
        "inputs": [('in', 'flow')],
        "outputs": [('then_0', 'flow'), ('then_1', 'flow'), ('next', 'flow')],
        "properties": {},
    },
    "set_active": {
        "title": "Set Active",
        "category": "Action",
        "inputs": [('in', 'flow'), ('target', 'object'), ('active', 'bool')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "active": True},
    },
    "set_hud": {
        "title": "Set Hud",
        "category": "UI",
        "inputs": [('in', 'flow'), ('text', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"text": ""},
    },
    "set_motion_speed": {
        "title": "Set Motion Speed",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('handle', 'movement'), ('speed', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"speed": 100.0},
    },
    "set_position": {
        "title": "Set Position",
        "category": "Position",
        "inputs": [('in', 'flow'), ('target', 'object'), ('x', 'number'), ('y', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "x": 0.0, "y": 0.0},
    },
    "set_position_x": {
        "title": "Set Position X",
        "category": "Position",
        "inputs": [('in', 'flow'), ('value', 'number'), ('target', 'object')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "value": 0.0},
    },
    "set_position_y": {
        "title": "Set Position Y",
        "category": "Position",
        "inputs": [('in', 'flow'), ('value', 'number'), ('target', 'object')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "value": 0.0},
    },
    "set_sprite": {
        "title": "Set Sprite",
        "category": "Graphics",
        "inputs": [('in', 'flow'), ('target', 'object'), ('path', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "path": ""},
    },
    "set_variable": {
        "title": "Set Variable",
        "category": "Variables",
        "inputs": [('in', 'flow'), ('value', 'any')],
        "outputs": [('next', 'flow')],
        "properties": {"name": "var_name", "value": 0.0},
    },
    "spawn_object": {
        "title": "Spawn Object",
        "category": "Spawning",
        "inputs": [('in', 'flow'), ('x', 'number'), ('y', 'number')],
        "outputs": [('next', 'flow'), ('object', 'object')],
        "properties": {"prefab_name": "NovoObjeto", "x": 0.0, "y": 0.0},
    },
    "start_continuous_motion": {
        "title": "Start Continuous Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('x', 'number'), ('y', 'number')],
        "outputs": [('next', 'flow'), ('movement', 'movement')],
        "properties": {"target": "", "speed_x": 100.0, "speed_y": 0.0},
    },
    "start_texture_scroll": {
        "title": "Start Texture Scroll",
        "category": "Text",
        "inputs": [('in', 'flow'), ('target', 'object'), ('path', 'text'), ('speed_x', 'number'), ('speed_y', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "path": "", "speed_x": 1.0, "speed_y": 0.0},
    },
    "stop_animation": {
        "title": "Stop Animation",
        "category": "Animation",
        "inputs": [('in', 'flow'), ('target', 'object')],
        "outputs": [('next', 'flow'), ('exec_failure', 'flow')],
        "properties": {"target": ""},
    },
    "stop_continuous_motion": {
        "title": "Stop Continuous Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('movement', 'movement')],
        "outputs": [('next', 'flow')],
        "properties": {"target": ""},
    },
    "stop_motion": {
        "title": "Stop Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('handle', 'movement')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "stop_texture_scroll": {
        "title": "Stop Texture Scroll",
        "category": "Text",
        "inputs": [('in', 'flow'), ('target', 'object')],
        "outputs": [('next', 'flow')],
        "properties": {"target": ""},
    },
    "subgraph_input": {
        "title": "Subgraph Input",
        "category": "Input",
        "inputs": [],
        "outputs": [('value', 'any')],
        "properties": {"input_name": "value"},
    },
    "subgraph_return": {
        "title": "Subgraph Return",
        "category": "Subgraphs",
        "inputs": [('in', 'flow'), ('value', 'any')],
        "outputs": [],
        "properties": {},
    },
    "subgraph_start": {
        "title": "Subgraph Start",
        "category": "Subgraphs",
        "inputs": [],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "subtract_number": {
        "title": "Subtract Number",
        "category": "Math",
        "inputs": [('a', 'number'), ('b', 'number')],
        "outputs": [('value', 'number')],
        "properties": {"a": 0.0, "b": 0.0},
    },
    "text_value": {
        "title": "Text Value",
        "category": "Text",
        "inputs": [],
        "outputs": [('value', 'text')],
        "properties": {"value": ""},
    },
    "to_text": {
        "title": "To Text",
        "category": "Text",
        "inputs": [('value', 'any')],
        "outputs": [('value', 'text')],
        "properties": {},
    },
    "update_continuous_motion": {
        "title": "Update Continuous Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('movement', 'movement'), ('x', 'number'), ('y', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "x": 0.0, "y": 0.0},
    },
    "animate_ui_value": {
        "title": "Animate UI Value",
        "category": "UI",
        "inputs": [('in', 'flow'), ('target_element', 'text'), ('target_value', 'number'), ('duration', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"target_element": "comida", "target_value": 0.0, "duration": 1.0, "easing": "linear"},
    },
    "start_dialogue": {
        "title": "Start Dialogue",
        "category": "UI",
        "inputs": [('in', 'flow'), ('npc', 'object')],
        "outputs": [('next', 'flow')],
        "properties": {"npc": ""},
    },
    "dialogue_choose": {
        "title": "Dialogue Choose Option",
        "category": "UI",
        "inputs": [('in', 'flow'), ('npc', 'object'), ('option_index', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"npc": "", "option_index": 0},
    },
    "animate_color": {
        "title": "Animate Color",
        "category": "Graphics",
        "inputs": [('in', 'flow'), ('target', 'object'), ('target_color', 'text'), ('duration', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "target_color": "#ffffff", "duration": 1.0, "easing": "ease_out"},
    },
    "animate_opacity": {
        "title": "Animate Opacity",
        "category": "Graphics",
        "inputs": [('in', 'flow'), ('target', 'object'), ('target_opacity', 'number'), ('duration', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "target_opacity": 1.0, "duration": 1.0, "easing": "ease_in"},
    },
    "set_animation_state": {
        "title": "Set Animation State",
        "category": "Animation",
        "inputs": [('in', 'flow'), ('target', 'object'), ('state_name', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "state_name": "Idle"},
    },
    "set_animation_parameter": {
        "title": "Set Animation Parameter",
        "category": "Animation",
        "inputs": [('in', 'flow'), ('target', 'object'), ('param_name', 'text'), ('value', 'any')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "param_name": "", "value": 0.0},
    },
    "set_ui_value": {
        "title": "Set UI Value",
        "category": "UI",
        "inputs": [('in', 'flow'), ('element', 'text'), ('value', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"element": "comida", "value": 100.0, "format": "{value}", "max_value": 100.0},
    },
    "increment_ui_value": {
        "title": "Increment UI Value",
        "category": "UI",
        "inputs": [('in', 'flow'), ('element', 'text'), ('amount', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"element": "comida", "amount": 10.0, "max_value": 100.0},
    },
    "decrement_ui_value": {
        "title": "Decrement UI Value",
        "category": "UI",
        "inputs": [('in', 'flow'), ('element', 'text'), ('amount', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"element": "comida", "amount": 10.0, "min_value": 0.0},
    },
    "animate_material": {
        "title": "Animate Material",
        "category": "UI",
        "inputs": [('in', 'flow'), ('target', 'object'), ('property', 'text'), ('target_value', 'number'), ('duration', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"target": "", "property": "", "target_value": 1.0, "duration": 1.0, "easing": "ease_in_out"},
    },
    "format_ui_text": {
        "title": "Format UI Text",
        "category": "UI",
        "inputs": [('in', 'flow'), ('element', 'text'), ('format_string', 'text'), ('value', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"element": "comida", "format_string": "{value}", "value": 0.0},
    },
    "get_parent": {
        "title": "Get Parent",
        "category": "Objects",
        "inputs": [('object', 'object')],
        "outputs": [('parent', 'object')],
        "properties": {"target": ""},
    },
    "get_child_by_index": {
        "title": "Get Child by Index",
        "category": "Objects",
        "inputs": [('object', 'object'), ('index', 'number')],
        "outputs": [('child', 'object')],
        "properties": {"target": "", "index": 0},
    },
    "get_children_count": {
        "title": "Get Children Count",
        "category": "Objects",
        "inputs": [('object', 'object')],
        "outputs": [('count', 'number')],
        "properties": {"target": ""},
    },
    "get_ui_widget_property": {
        "title": "Obter Propriedade Widget",
        "category": "UI",
        "inputs": [('in', 'flow'), ('parent', 'text'), ('widget_name', 'text'), ('property', 'text')],
        "outputs": [('next', 'flow'), ('value', 'text')],
        "properties": {"parent": "", "widget_name": "comida", "property": "value"},
    },
    "get_progress_bar_value": {
        "title": "Ler Valor ProgressBar",
        "category": "UI",
        "inputs": [('in', 'flow'), ('widget_name', 'text')],
        "outputs": [('next', 'flow'), ('value', 'number')],
        "properties": {"widget_name": "comida"},
    },
    "bind_ui_to_variable": {
        "title": "Vincular UI → Variável",
        "category": "UI",
        "inputs": [('in', 'flow'), ('widget_name', 'text'), ('variable_name', 'text'), ('property', 'text')],
        "outputs": [('next', 'flow'), ('exec_success', 'flow'), ('exec_not_found', 'flow'), ('exec_failure', 'flow')],
        "properties": {"widget_name": "comida", "variable_name": "comida", "property": "value"},
    },
    "update_ui_binding": {
        "title": "Atualizar Binding UI",
        "category": "UI",
        "inputs": [('in', 'flow'), ('widget_name', 'text'), ('variable_name', 'text'), ('property', 'text')],
        "outputs": [('next', 'flow'), ('exec_success', 'flow'), ('exec_not_found', 'flow'), ('exec_failure', 'flow')],
        "properties": {"widget_name": "comida", "variable_name": "comida", "property": "value"},
    },
}
