"""Definição declarativa de todos os nós nativos do Logic Graph da Zennity Engine."""

from __future__ import annotations

from typing import Any

NODE_DEFINITIONS: dict[str, dict[str, Any]] = {
    "event_start": {
        "title": "Ao Iniciar",
        "category": "Eventos",
        "inputs": [],
        "outputs": [("next", "flow")],
        "properties": {},
    },
    "event_update": {
        "title": "A Cada Frame",
        "category": "Eventos",
        "inputs": [],
        "outputs": [("next", "flow")],
        "properties": {},
    },
    "event_custom": {
        "title": "Ao Receber Evento",
        "category": "Eventos",
        "inputs": [],
        "outputs": [("next", "flow"), ("payload", "any")],
        "properties": {"name": "game_started"},
    },
    "event_key_pressed": {
        "title": "Tecla Pressionada",
        "category": "Eventos",
        "inputs": [],
        "outputs": [("next", "flow")],
        "properties": {"key": "SPACE"},
    },
    "event_collision_enter": {
        "title": "Ao Colidir",
        "category": "Eventos",
        "inputs": [],
        "outputs": [("next", "flow"), ("other", "object")],
        "properties": {"tag": ""},
    },
    "event_trigger_enter": {
        "title": "Ao Entrar no Trigger",
        "category": "Eventos",
        "inputs": [],
        "outputs": [("next", "flow"), ("other", "object")],
        "properties": {"tag": ""},
    },
    "event_created": {
        "title": "Ao Criar Objeto",
        "category": "Eventos",
        "inputs": [],
        "outputs": [("next", "flow"), ("created_object", "object")],
        "properties": {},
    },
    "event_spawn_limit_reached": {
        "title": "Limite Alcançado",
        "category": "Eventos",
        "inputs": [],
        "outputs": [("next", "flow")],
        "properties": {"limit": 10},
    },
    "event_timer": {
        "title": "Temporizador",
        "category": "Eventos",
        "inputs": [],
        "outputs": [("next", "flow")],
        "properties": {"interval": 1.0, "repeat": True},
    },
    "move_x": {
        "title": "Mover X",
        "category": "Movimento",
        "inputs": [("in", "flow"), ("speed", "number"), ("target", "object")],
        "outputs": [("next", "flow"), ("handle", "movement")],
        "properties": {"speed": 180.0, "space": "local"},
    },
    "move_y": {
        "title": "Mover Y",
        "category": "Movimento",
        "inputs": [("in", "flow"), ("speed", "number"), ("target", "object")],
        "outputs": [("next", "flow"), ("handle", "movement")],
        "properties": {"speed": 180.0, "space": "local"},
    },
    "move_towards": {
        "title": "Mover na Direção de",
        "category": "Movimento",
        "inputs": [("in", "flow"), ("speed", "number"), ("destination_x", "number"), ("destination_y", "number"), ("target", "object")],
        "outputs": [("next", "flow"), ("handle", "movement")],
        "properties": {"speed": 180.0, "space": "world"},
    },
    "jump": {
        "title": "Pular",
        "category": "Movimento",
        "inputs": [("in", "flow"), ("force", "number"), ("target", "object")],
        "outputs": [("next", "flow")],
        "properties": {"force": 420.0},
    },
    "rotate": {
        "title": "Girar",
        "category": "Movimento",
        "inputs": [("in", "flow"), ("speed", "number"), ("target", "object")],
        "outputs": [("next", "flow"), ("handle", "movement")],
        "properties": {"speed": 90.0},
    },
    "set_motion_speed": {
        "title": "Alterar Velocidade do Movimento",
        "category": "Movimento",
        "inputs": [("in", "flow"), ("handle", "movement"), ("speed", "number")],
        "outputs": [("next", "flow")],
        "properties": {"speed": 220.0},
    },
    "pause_motion": {
        "title": "Pausar Movimento",
        "category": "Movimento",
        "inputs": [("in", "flow"), ("handle", "movement")],
        "outputs": [("next", "flow")],
        "properties": {},
    },
    "resume_motion": {
        "title": "Retomar Movimento",
        "category": "Movimento",
        "inputs": [("in", "flow"), ("handle", "movement")],
        "outputs": [("next", "flow")],
        "properties": {},
    },
    "stop_motion": {
        "title": "Parar Movimento",
        "category": "Movimento",
        "inputs": [("in", "flow"), ("handle", "movement")],
        "outputs": [("next", "flow")],
        "properties": {},
    },
    "motion_state_query": {
        "title": "Consultar Movimento",
        "category": "Movimento",
        "inputs": [("handle", "movement")],
        "outputs": [("active", "bool"), ("current_speed", "number")],
        "properties": {},
    },
    "get_position_x": {
        "title": "Obter X Atual",
        "category": "Posição",
        "inputs": [("target", "object")],
        "outputs": [("value", "number")],
        "properties": {},
    },
    "get_position_y": {
        "title": "Obter Y Atual",
        "category": "Posição",
        "inputs": [("target", "object")],
        "outputs": [("value", "number")],
        "properties": {},
    },
    "set_position_x": {
        "title": "Definir X",
        "category": "Posição",
        "inputs": [("in", "flow"), ("value", "number"), ("target", "object")],
        "outputs": [("next", "flow")],
        "properties": {"value": 0.0},
    },
    "set_position_y": {
        "title": "Definir Y",
        "category": "Posição",
        "inputs": [("in", "flow"), ("value", "number"), ("target", "object")],
        "outputs": [("next", "flow")],
        "properties": {"value": 0.0},
    },
    "destroy_object": {
        "title": "Destruir Objeto",
        "category": "Ação",
        "inputs": [("in", "flow"), ("target", "object")],
        "outputs": [("next", "flow")],
        "properties": {},
    },
    "spawn_object": {
        "title": "Criar Objeto",
        "category": "Ação",
        "inputs": [("in", "flow"), ("x", "number"), ("y", "number")],
        "outputs": [("next", "flow"), ("created_object", "object")],
        "properties": {"name": "Particle", "mesh_type": "rect", "x": 0.0, "y": 0.0, "w": 16.0, "h": 16.0},
    },
    "create_prefab": {
        "title": "Instanciar Prefab",
        "category": "Ação",
        "inputs": [("in", "flow"), ("x", "number"), ("y", "number")],
        "outputs": [("next", "flow"), ("created_object", "object")],
        "properties": {"path": "Assets/Prefabs/Bullet.zprefab", "override_scale": False, "width": 32.0, "height": 32.0},
    },
    "get_prefab_parameter": {
        "title": "Parâmetro do Prefab",
        "category": "Ação",
        "inputs": [],
        "outputs": [("value", "text")],
        "properties": {"name": "speed", "type": "text"},
    },
    "emit_event": {
        "title": "Enviar Evento",
        "category": "Ação",
        "inputs": [("in", "flow"), ("payload", "any")],
        "outputs": [("next", "flow")],
        "properties": {"name": "game_started"},
    },
    "set_sprite": {
        "title": "Trocar Imagem",
        "category": "Ação",
        "inputs": [("in", "flow"), ("path", "text"), ("target", "object")],
        "outputs": [("next", "flow")],
        "properties": {"path": "Assets/Textures/player.png"},
    },
    "set_texture_scroll": {
        "title": "Rolar Fundo",
        "category": "Ação",
        "inputs": [("in", "flow"), ("speed_x", "number"), ("speed_y", "number"), ("target", "object")],
        "outputs": [("next", "flow")],
        "properties": {"enabled": True, "speed_x": -60.0, "speed_y": 0.0, "parallax": 1.0},
    },
    "stop_texture_scroll": {
        "title": "Parar Rolar Fundo",
        "category": "Ação",
        "inputs": [("in", "flow"), ("target", "object")],
        "outputs": [("next", "flow")],
        "properties": {},
    },
    "play_animation_asset": {
        "title": "Tocar Animação",
        "category": "Ação",
        "inputs": [("in", "flow"), ("path", "text"), ("target", "object")],
        "outputs": [("next", "flow")],
        "properties": {"path": "Assets/Animations/walk.zanim"},
    },
    "play_sound": {
        "title": "Tocar Som",
        "category": "Ação",
        "inputs": [("in", "flow"), ("path", "text"), ("volume", "number"), ("target", "object")],
        "outputs": [("next", "flow")],
        "properties": {"path": "Assets/Audio/jump.wav", "volume": 1.0},
    },
    "update_hud_text": {
        "title": "Atualizar Texto do HUD",
        "category": "Ação",
        "inputs": [("in", "flow"), ("text", "text")],
        "outputs": [("next", "flow")],
        "properties": {"element_id": "hud_score", "text": "Score: 0"},
    },
    "cooldown": {
        "title": "Cooldown",
        "category": "Lógica",
        "inputs": [("in", "flow"), ("duration", "number")],
        "outputs": [("next", "flow")],
        "properties": {"duration": 0.5},
    },
    "sequence": {
        "title": "Sequência",
        "category": "Lógica",
        "inputs": [("in", "flow")],
        "outputs": [("then_1", "flow"), ("then_2", "flow")],
        "properties": {},
    },
    "once": {
        "title": "Executar Uma Vez",
        "category": "Lógica",
        "inputs": [("in", "flow")],
        "outputs": [("next", "flow")],
        "properties": {},
    },
    "branch": {
        "title": "Se / Senão",
        "category": "Condição",
        "inputs": [("in", "flow"), ("condition", "bool")],
        "outputs": [("true", "flow"), ("false", "flow")],
        "properties": {},
    },
    "key_held": {
        "title": "Tecla Segurada",
        "category": "Condição",
        "inputs": [],
        "outputs": [("is_down", "bool")],
        "properties": {"key": "A"},
    },
    "is_grounded": {
        "title": "No Chão?",
        "category": "Condição",
        "inputs": [("target", "object")],
        "outputs": [("is_grounded", "bool")],
        "properties": {},
    },
    "compare_numbers": {
        "title": "Comparar Números",
        "category": "Condição",
        "inputs": [("a", "number"), ("b", "number")],
        "outputs": [("result", "bool")],
        "properties": {"operator": ">=", "a": 0.0, "b": 0.0},
    },
    "find_by_name": {
        "title": "Buscar por Nome",
        "category": "Objetos",
        "inputs": [],
        "outputs": [("object", "object")],
        "properties": {"name": "Player"},
    },
    "find_by_tag": {
        "title": "Buscar por Tag",
        "category": "Objetos",
        "inputs": [],
        "outputs": [("object", "object")],
        "properties": {"tag": "Enemy"},
    },
    "get_tag": {
        "title": "Obter Tag do Objeto",
        "category": "Objetos",
        "inputs": [("target", "object")],
        "outputs": [("tag", "text")],
        "properties": {},
    },
    "get_variable": {
        "title": "Obter Variável",
        "category": "Variáveis",
        "inputs": [],
        "outputs": [("value", "any")],
        "properties": {"name": "score", "scope": "scene"},
    },
    "set_variable": {
        "title": "Definir Variável",
        "category": "Variáveis",
        "inputs": [("in", "flow"), ("value", "any")],
        "outputs": [("next", "flow")],
        "properties": {"name": "score", "scope": "scene", "value": 0},
    },
    "subgraph_input": {
        "title": "Entrada do Subgrafo",
        "category": "Subgrafos",
        "inputs": [],
        "outputs": [("value", "any")],
        "properties": {"name": "amount", "type": "number", "default": 1.0},
    },
    "subgraph_return": {
        "title": "Retorno do Subgrafo",
        "category": "Subgrafos",
        "inputs": [("in", "flow"), ("value", "any")],
        "outputs": [],
        "properties": {"name": "result", "type": "any"},
    },
    "call_subgraph": {
        "title": "Chamar Subgrafo",
        "category": "Subgrafos",
        "inputs": [("in", "flow")],
        "outputs": [("next", "flow")],
        "properties": {"path": "Assets/Logic/ReusableHelper.zlogic", "inputs": [], "outputs": []},
    },
    "number_value": {
        "title": "Número",
        "category": "Matemática",
        "inputs": [],
        "outputs": [("value", "number")],
        "properties": {"value": 0.0},
    },
    "bool_value": {
        "title": "Booleano",
        "category": "Matemática",
        "inputs": [],
        "outputs": [("value", "bool")],
        "properties": {"value": True},
    },
    "text_value": {
        "title": "Texto Fixo",
        "category": "Texto",
        "inputs": [],
        "outputs": [("value", "text")],
        "properties": {"value": "Zennity"},
    },
    "add_number": {
        "title": "Somar",
        "category": "Matemática",
        "inputs": [("a", "number"), ("b", "number")],
        "outputs": [("value", "number")],
        "properties": {"a": 0.0, "b": 1.0},
    },
    "subtract_number": {
        "title": "Subtrair",
        "category": "Matemática",
        "inputs": [("a", "number"), ("b", "number")],
        "outputs": [("value", "number")],
        "properties": {"a": 0.0, "b": 1.0},
    },
    "multiply_number": {
        "title": "Multiplicar",
        "category": "Matemática",
        "inputs": [("a", "number"), ("b", "number")],
        "outputs": [("value", "number")],
        "properties": {"a": 1.0, "b": 1.0},
    },
    "divide_number": {
        "title": "Dividir",
        "category": "Matemática",
        "inputs": [("a", "number"), ("b", "number")],
        "outputs": [("value", "number")],
        "properties": {"a": 1.0, "b": 1.0},
    },
    "absolute_number": {
        "title": "Valor Absoluto (ABS)",
        "category": "Matemática",
        "inputs": [("value", "number")],
        "outputs": [("result", "number")],
        "properties": {"value": -5.0},
    },
    "clamp_number": {
        "title": "Limitar (Clamp)",
        "category": "Matemática",
        "inputs": [("value", "number"), ("min", "number"), ("max", "number")],
        "outputs": [("result", "number")],
        "properties": {"value": 5.0, "min": 0.0, "max": 10.0},
    },
    "random_number": {
        "title": "Número Aleatório",
        "category": "Matemática",
        "inputs": [("min", "number"), ("max", "number")],
        "outputs": [("value", "number")],
        "properties": {"min": 0.0, "max": 1.0},
    },
    "delta_time": {
        "title": "Tempo por Frame (Delta)",
        "category": "Matemática",
        "inputs": [],
        "outputs": [("value", "number")],
        "properties": {},
    },
    "join_text": {
        "title": "Juntar Textos",
        "category": "Texto",
        "inputs": [("a", "text"), ("b", "text")],
        "outputs": [("value", "text")],
        "properties": {"a": "Score: ", "b": ""},
    },
    "to_text": {
        "title": "Converter para Texto",
        "category": "Texto",
        "inputs": [("value", "any")],
        "outputs": [("text", "text")],
        "properties": {},
    },
}

# Definitions retained from the pre-extraction public catalog.  Keeping them
# here makes the declarative module the single source of truth.
NODE_DEFINITIONS.update({
    "create_object": {"title": "Create Object", "category": "Objects", "properties": {
        "name": "NewObject", "x": 0.0, "y": 0.0, "width": 64.0, "height": 64.0,
        "color": "#58a6ff", "texture": "", "tag": "Untagged", "relative": False,
        "inherit_source": True, "inherit_logic": False, "lifetime": 0.0,
        "max_instances": 0, "max_distance": 0.0, "use_pool": False,
    }},
    "create_prefab": {"title": "Create Prefab", "category": "Objects", "properties": {
        "path": "", "override_position": True, "x": 0.0, "y": 0.0, "relative": False,
        "override_rotation": False, "rotation": 0.0, "override_scale": False,
        "width": 64.0, "height": 64.0, "include_camera": False,
        "include_audio": False, "include_logic": False, "parameters": {},
        "exposed_properties": [], "lifetime": 0.0, "max_instances": 0,
        "max_distance": 0.0, "use_pool": True,
    }},
    "clone_object": {"title": "Clone Object", "category": "Objects", "properties": {
        "name": "", "lifetime": 0.0, "max_instances": 0,
        "max_distance": 0.0, "use_pool": False,
    }},
    "event_object_created": {"title": "On Object Created", "category": "Events", "properties": {}},
    "destroy_after_time": {"title": "Destroy After Time", "category": "Action", "properties": {"seconds": 2.0}},
    "start_continuous_motion": {"title": "Start Continuous Motion", "category": "Position", "properties": {
        "movement": "Movement", "x": 100.0, "y": 0.0, "space": "global",
        "acceleration": 0.0, "deceleration": 0.0,
    }},
    "update_continuous_motion": {"title": "Update Continuous Motion", "category": "Position", "properties": {
        "movement": "Movement", "x": 100.0, "y": 0.0, "acceleration": 0.0,
    }},
    "pause_continuous_motion": {"title": "Pause Continuous Motion", "category": "Position", "properties": {"movement": "Movement"}},
    "resume_continuous_motion": {"title": "Resume Continuous Motion", "category": "Position", "properties": {"movement": "Movement"}},
    "stop_continuous_motion": {"title": "Stop Continuous Motion", "category": "Position", "properties": {"movement": "", "smooth": False}},
    "get_continuous_motion": {"title": "Get Continuous Motion", "category": "Position", "properties": {"movement": "Movement"}},
})
