"""Declarative definitions of all native visual logic nodes in the Zennity Engine."""

from __future__ import annotations

from typing import Any

NODE_DEFINITIONS: dict[str, dict[str, Any]] = {
    "absolute_number": {
        "title": "Absolute Number",
        "category": "Math",
        "inputs": [('value', 'number')],
        "outputs": [('value', 'number')],
        "properties": {},
    },
    "add_component": {
        "title": "Add Component",
        "category": "Math",
        "inputs": [('in', 'flow'), ('target', 'object')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "add_number": {
        "title": "Add Number",
        "category": "Math",
        "inputs": [('a', 'number'), ('b', 'number')],
        "outputs": [('value', 'number')],
        "properties": {},
    },
    "and": {
        "title": "And",
        "category": "Logic",
        "inputs": [('a', 'bool'), ('b', 'bool')],
        "outputs": [('value', 'bool')],
        "properties": {},
    },
    "bool_value": {
        "title": "Bool Value",
        "category": "Action",
        "inputs": [],
        "outputs": [('value', 'bool')],
        "properties": {},
    },
    "call_subgraph": {
        "title": "Call Subgraph",
        "category": "Subgraphs",
        "inputs": [('in', 'flow')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "clamp_number": {
        "title": "Clamp Number",
        "category": "Math",
        "inputs": [('value', 'number'), ('minimum', 'number'), ('maximum', 'number')],
        "outputs": [('value', 'number')],
        "properties": {},
    },
    "clone_object": {
        "title": "Clone Object",
        "category": "Spawning",
        "inputs": [('in', 'flow'), ('target', 'object'), ('name', 'text')],
        "outputs": [('next', 'flow'), ('limit_reached', 'flow'), ('object', 'object')],
        "properties": {},
    },
    "compare_number": {
        "title": "Compare Number",
        "category": "Logic",
        "inputs": [('in', 'flow'), ('value', 'number')],
        "outputs": [('true', 'flow'), ('false', 'flow'), ('value', 'bool')],
        "properties": {"operator": ">", "value": 0.0},
    },
    "compare_text": {
        "title": "Compare Text",
        "category": "Logic",
        "inputs": [('in', 'flow'), ('value', 'text')],
        "outputs": [('true', 'flow'), ('false', 'flow'), ('value', 'bool')],
        "properties": {"operator": "==", "value": ""},
    },
    "cooldown": {
        "title": "Cooldown",
        "category": "Logic",
        "inputs": [('in', 'flow'), ('seconds', 'number')],
        "outputs": [('next', 'flow'), ('blocked', 'flow')],
        "properties": {"seconds": 1.0},
    },
    "create_object": {
        "title": "Create Object",
        "category": "Spawning",
        "inputs": [('in', 'flow'), ('source', 'object'), ('name', 'text'), ('x', 'number'), ('y', 'number')],
        "outputs": [('next', 'flow'), ('limit_reached', 'flow'), ('object', 'object')],
        "properties": {},
    },
    "create_prefab": {
        "title": "Create Prefab",
        "category": "Spawning",
        "inputs": [('in', 'flow'), ('x', 'number'), ('y', 'number'), ('rotation', 'number'), ('width', 'number'), ('height', 'number')],
        "outputs": [('next', 'flow'), ('limit_reached', 'flow'), ('object', 'object')],
        "properties": {},
    },
    "delta_time": {
        "title": "Delta Time",
        "category": "Math",
        "inputs": [],
        "outputs": [('value', 'number')],
        "properties": {},
    },
    "destroy_after_time": {
        "title": "Destroy After Time",
        "category": "Action",
        "inputs": [('in', 'flow'), ('target', 'object'), ('seconds', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"seconds": 1.0},
    },
    "destroy_object": {
        "title": "Destroy Object",
        "category": "Action",
        "inputs": [('in', 'flow'), ('target', 'object')],
        "outputs": [],
        "properties": {},
    },
    "start_behavior_tree": {
        "title": "Start Behavior Tree",
        "category": "Action",
        "inputs": [('in', 'flow'), ('target', 'object'), ('path', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"path": "Assets/Behaviors/patrol_comida.zbehavior"},
    },
    "divide_number": {
        "title": "Divide Number",
        "category": "Math",
        "inputs": [('a', 'number'), ('b', 'number')],
        "outputs": [('value', 'number')],
        "properties": {},
    },
    "emit_event": {
        "title": "Emit Event",
        "category": "Events",
        "inputs": [('in', 'flow'), ('payload', 'any')],
        "outputs": [('next', 'flow')],
        "properties": {"event_name": "MyEvent"},
    },
    "event_collision_enter": {
        "title": "Event Collision Enter",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('other', 'object')],
        "properties": {},
    },
    "event_collision_exit": {
        "title": "Event Collision Exit",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('other', 'object')],
        "properties": {},
    },
    "event_created": {
        "title": "Event Created",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('created_object', 'object')],
        "properties": {},
    },
    "event_custom": {
        "title": "Event Custom",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('payload', 'any')],
        "properties": {"event_name": "MyEvent"},
    },
    "event_key_pressed": {
        "title": "Event Key Pressed",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow')],
        "properties": {"key": "SPACE"},
    },
    "event_object_created": {
        "title": "Event Object Created",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('object', 'object')],
        "properties": {},
    },
    "event_spawn_limit_reached": {
        "title": "Event Spawn Limit Reached",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "event_start": {
        "title": "Event Start",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "event_timer": {
        "title": "Event Timer",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow')],
        "properties": {"seconds": 1.0},
    },
    "event_trigger_enter": {
        "title": "Event Trigger Enter",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('other', 'object')],
        "properties": {},
    },
    "event_trigger_exit": {
        "title": "Event Trigger Exit",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow'), ('other', 'object')],
        "properties": {},
    },
    "event_update": {
        "title": "Event Update",
        "category": "Events",
        "inputs": [],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "find_tag": {
        "title": "Find Tag",
        "category": "Objects",
        "inputs": [('in', 'flow')],
        "outputs": [('next', 'flow'), ('object', 'object')],
        "properties": {"tag": "Player"},
    },
    "get_continuous_motion": {
        "title": "Get Continuous Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('movement', 'movement')],
        "outputs": [('next', 'flow'), ('x', 'number'), ('y', 'number'), ('speed', 'number'), ('paused', 'bool'), ('active', 'bool')],
        "properties": {},
    },
    "get_position": {
        "title": "Get Position",
        "category": "Position",
        "inputs": [('target', 'object')],
        "outputs": [('x', 'number'), ('y', 'number')],
        "properties": {},
    },
    "get_position_x": {
        "title": "Get Position X",
        "category": "Position",
        "inputs": [('target', 'object')],
        "outputs": [('value', 'number')],
        "properties": {},
    },
    "get_position_y": {
        "title": "Get Position Y",
        "category": "Position",
        "inputs": [('target', 'object')],
        "outputs": [('value', 'number')],
        "properties": {},
    },
    "get_prefab_parameter": {
        "title": "Get Prefab Parameter",
        "category": "Action",
        "inputs": [('target', 'object')],
        "outputs": [('value', 'any')],
        "properties": {},
    },
    "get_tag": {
        "title": "Get Tag",
        "category": "Objects",
        "inputs": [('target', 'object')],
        "outputs": [('value', 'text')],
        "properties": {"tag": "Player"},
    },
    "get_variable": {
        "title": "Get Variable",
        "category": "Variables",
        "inputs": [('in', 'flow')],
        "outputs": [('next', 'flow'), ('value', 'any')],
        "properties": {"name": "var_name"},
    },
    "if_else": {
        "title": "If Else",
        "category": "Logic",
        "inputs": [('in', 'flow'), ('condition', 'bool')],
        "outputs": [('true', 'flow'), ('false', 'flow')],
        "properties": {"condition": False},
    },
    "input_axis": {
        "title": "Read Key Axis",
        "category": "Input",
        "inputs": [('in', 'flow')],
        "outputs": [('next', 'flow'), ('value', 'number')],
        "properties": {"negative": "A", "positive": "D"},
    },
    "is_grounded": {
        "title": "Is Grounded",
        "category": "Action",
        "inputs": [('in', 'flow')],
        "outputs": [('true', 'flow'), ('false', 'flow'), ('value', 'bool')],
        "properties": {},
    },
    "join_text": {
        "title": "Join Text",
        "category": "Text",
        "inputs": [('a', 'any'), ('b', 'any')],
        "outputs": [('value', 'text')],
        "properties": {},
    },
    "jump": {
        "title": "Jump",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('force', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "key_held": {
        "title": "Key Held",
        "category": "Input",
        "inputs": [('in', 'flow')],
        "outputs": [('true', 'flow'), ('false', 'flow'), ('value', 'bool')],
        "properties": {"key": "SPACE"},
    },
    "key_pressed": {
        "title": "Key Pressed",
        "category": "Input",
        "inputs": [('in', 'flow')],
        "outputs": [('true', 'flow'), ('false', 'flow'), ('value', 'bool')],
        "properties": {"key": "SPACE"},
    },
    "log_message": {
        "title": "Log Message",
        "category": "Action",
        "inputs": [('in', 'flow'), ('text', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"message": "Log message"},
    },
    "motion_state_query": {
        "title": "Motion State Query",
        "category": "Movement",
        "inputs": [('handle', 'movement')],
        "outputs": [('active', 'bool'), ('current_speed', 'number')],
        "properties": {},
    },
    "move": {
        "title": "Move",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('value', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"speed": 100.0},
    },
    "move_by": {
        "title": "Move By",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('x', 'number'), ('y', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"x": 100.0, "y": 0.0},
    },
    "move_towards": {
        "title": "Move Towards",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('speed', 'number'), ('destination_x', 'number'), ('destination_y', 'number'), ('target', 'object')],
        "outputs": [('next', 'flow'), ('handle', 'movement')],
        "properties": {"speed": 100.0, "destination_x": 0.0, "destination_y": 0.0},
    },
    "move_x": {
        "title": "Move X",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('speed', 'number'), ('target', 'object')],
        "outputs": [('next', 'flow'), ('handle', 'movement')],
        "properties": {"speed": 100.0},
    },
    "move_y": {
        "title": "Move Y",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('speed', 'number'), ('target', 'object')],
        "outputs": [('next', 'flow'), ('handle', 'movement')],
        "properties": {"speed": 100.0},
    },
    "multiply_number": {
        "title": "Multiply Number",
        "category": "Math",
        "inputs": [('a', 'number'), ('b', 'number')],
        "outputs": [('value', 'number')],
        "properties": {},
    },
    "not": {
        "title": "Not",
        "category": "Logic",
        "inputs": [('value', 'bool')],
        "outputs": [('value', 'bool')],
        "properties": {},
    },
    "number_value": {
        "title": "Number Value",
        "category": "Math",
        "inputs": [],
        "outputs": [('value', 'number')],
        "properties": {"value": 0.0},
    },
    "once": {
        "title": "Once",
        "category": "Logic",
        "inputs": [('in', 'flow')],
        "outputs": [('next', 'flow'), ('blocked', 'flow')],
        "properties": {},
    },
    "or": {
        "title": "Or",
        "category": "Logic",
        "inputs": [('a', 'bool'), ('b', 'bool')],
        "outputs": [('value', 'bool')],
        "properties": {},
    },
    "patrol_axis": {
        "title": "Patrol Axis",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('minimum', 'number'), ('maximum', 'number'), ('speed', 'number')],
        "outputs": [('next', 'flow'), ('direction', 'number'), ('position', 'number')],
        "properties": {"minimum": -100.0, "maximum": 100.0, "speed": 100.0},
    },
    "pause_continuous_motion": {
        "title": "Pause Continuous Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('movement', 'movement')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "pause_motion": {
        "title": "Pause Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('handle', 'movement')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "play_animation": {
        "title": "Play Animation",
        "category": "Animation",
        "inputs": [('in', 'flow'), ('state', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"state": "Idle"},
    },
    "play_animation_asset": {
        "title": "Play Animation Asset",
        "category": "Animation",
        "inputs": [('in', 'flow'), ('path', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"path": ""},
    },
    "play_sound": {
        "title": "Play Sound",
        "category": "Audio",
        "inputs": [('in', 'flow'), ('path', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"path": ""},
    },
    "set_ui_text": {
        "title": "Atualizar texto da UI", "category": "UI",
        "inputs": [('in', 'flow'), ('text', 'text')], "outputs": [('next', 'flow')],
        "properties": {"object": "", "text": ""},
    },
    "set_ui_progress_bar": {
        "title": "Atualizar barra da UI", "category": "UI",
        "inputs": [('in', 'flow'), ('value', 'number')], "outputs": [('next', 'flow')],
        "properties": {"object": "", "value": 100.0, "max_value": 100.0},
    },
    "random_number": {
        "title": "Random Number",
        "category": "Logic",
        "inputs": [('minimum', 'number'), ('maximum', 'number')],
        "outputs": [('value', 'number')],
        "properties": {"minimum": 0.0, "maximum": 1.0},
    },
    "remove_component": {
        "title": "Remove Component",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "restart_scene": {
        "title": "Restart Scene",
        "category": "Action",
        "inputs": [('in', 'flow')],
        "outputs": [],
        "properties": {},
    },
    "resume_continuous_motion": {
        "title": "Resume Continuous Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('movement', 'movement')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "resume_motion": {
        "title": "Resume Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('handle', 'movement')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "rotate": {
        "title": "Rotate",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('degrees', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"degrees": 90.0},
    },
    "self_object": {
        "title": "Self Object",
        "category": "Objects",
        "inputs": [],
        "outputs": [('object', 'object')],
        "properties": {},
    },
    "sequence": {
        "title": "Sequence",
        "category": "Logic",
        "inputs": [('in', 'flow')],
        "outputs": [('then_0', 'flow'), ('then_1', 'flow'), ('next', 'flow')],
        "properties": {},
    },
    "set_active": {
        "title": "Set Active",
        "category": "Action",
        "inputs": [('in', 'flow'), ('target', 'object'), ('active', 'bool')],
        "outputs": [('next', 'flow')],
        "properties": {"active": True},
    },
    "set_hud": {
        "title": "Set Hud",
        "category": "UI",
        "inputs": [('in', 'flow'), ('text', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"text": ""},
    },
    "set_motion_speed": {
        "title": "Set Motion Speed",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('handle', 'movement'), ('speed', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"speed": 100.0},
    },
    "set_position": {
        "title": "Set Position",
        "category": "Position",
        "inputs": [('in', 'flow'), ('target', 'object'), ('x', 'number'), ('y', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {"x": 0.0, "y": 0.0},
    },
    "set_position_x": {
        "title": "Set Position X",
        "category": "Position",
        "inputs": [('in', 'flow'), ('value', 'number'), ('target', 'object')],
        "outputs": [('next', 'flow')],
        "properties": {"value": 0.0},
    },
    "set_position_y": {
        "title": "Set Position Y",
        "category": "Position",
        "inputs": [('in', 'flow'), ('value', 'number'), ('target', 'object')],
        "outputs": [('next', 'flow')],
        "properties": {"value": 0.0},
    },
    "set_sprite": {
        "title": "Set Sprite",
        "category": "Graphics",
        "inputs": [('in', 'flow'), ('target', 'object'), ('path', 'text')],
        "outputs": [('next', 'flow')],
        "properties": {"path": ""},
    },
    "set_variable": {
        "title": "Set Variable",
        "category": "Variables",
        "inputs": [('in', 'flow'), ('value', 'any')],
        "outputs": [('next', 'flow')],
        "properties": {"name": "var_name", "value": 0.0},
    },
    "spawn_object": {
        "title": "Spawn Object",
        "category": "Spawning",
        "inputs": [('in', 'flow'), ('x', 'number'), ('y', 'number')],
        "outputs": [('next', 'flow'), ('object', 'object')],
        "properties": {},
    },
    "start_continuous_motion": {
        "title": "Start Continuous Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('x', 'number'), ('y', 'number')],
        "outputs": [('next', 'flow'), ('movement', 'movement')],
        "properties": {},
    },
    "start_texture_scroll": {
        "title": "Start Texture Scroll",
        "category": "Text",
        "inputs": [('in', 'flow'), ('target', 'object'), ('path', 'text'), ('speed_x', 'number'), ('speed_y', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "stop_animation": {
        "title": "Stop Animation",
        "category": "Animation",
        "inputs": [('in', 'flow')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "stop_continuous_motion": {
        "title": "Stop Continuous Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('movement', 'movement')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "stop_motion": {
        "title": "Stop Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('handle', 'movement')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "stop_texture_scroll": {
        "title": "Stop Texture Scroll",
        "category": "Text",
        "inputs": [('in', 'flow'), ('target', 'object')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "subgraph_input": {
        "title": "Subgraph Input",
        "category": "Input",
        "inputs": [],
        "outputs": [('value', 'any')],
        "properties": {},
    },
    "subgraph_return": {
        "title": "Subgraph Return",
        "category": "Subgraphs",
        "inputs": [('in', 'flow'), ('value', 'any')],
        "outputs": [],
        "properties": {},
    },
    "subgraph_start": {
        "title": "Subgraph Start",
        "category": "Subgraphs",
        "inputs": [],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
    "subtract_number": {
        "title": "Subtract Number",
        "category": "Math",
        "inputs": [('a', 'number'), ('b', 'number')],
        "outputs": [('value', 'number')],
        "properties": {},
    },
    "text_value": {
        "title": "Text Value",
        "category": "Text",
        "inputs": [],
        "outputs": [('value', 'text')],
        "properties": {},
    },
    "to_text": {
        "title": "To Text",
        "category": "Text",
        "inputs": [('value', 'any')],
        "outputs": [('value', 'text')],
        "properties": {},
    },
    "update_continuous_motion": {
        "title": "Update Continuous Motion",
        "category": "Movement",
        "inputs": [('in', 'flow'), ('target', 'object'), ('movement', 'movement'), ('x', 'number'), ('y', 'number')],
        "outputs": [('next', 'flow')],
        "properties": {},
    },
}
