
LOGIC_RECIPES_PART_1 = (

    {
        "id": "safe_pooled_projectile",
        "topics": ("Objects", "Creation", "Movement", "Input"),
        "title": "Shoot Pooled Projectile",
        "category": "Objects & Scene",
        "summary": "Creates projectiles on Spacebar press, limits instances, moves each copy, and reuses them via pooling.",
        "keywords": "projectile shoot bullet pool limit life distance create key movement permanent",
        "steps": (
            "Pressing Space triggers once per press.",
            "Create Object creates a Projectile, which automatically becomes the target of the next block.",
            "A maximum of 20 projectiles remain active; each lives for 3 seconds or travels 1200 units.",
            "The pool reuses discarded instances, reducing repeated allocation overhead.",
            "Start Continuous Motion implicitly targets the newly created Projectile.",
        ),
        "nodes": (
            {"key": "key", "type": "event_key_pressed", "position": (0.0, 0.0), "properties": {"key": "SPACE"}},
            {
                "key": "create", "type": "create_object", "position": (300.0, 0.0),
                "properties": {
                    "name": "Projectile", "x": 0.0, "y": 0.0,
                    "width": 20.0, "height": 10.0, "color": "#ffd166",
                    "texture": "", "tag": "Projectile", "relative": True,
                    "inherit_source": False, "inherit_logic": False,
                    "lifetime": 3.0, "max_instances": 20,
                    "max_distance": 1200.0, "use_pool": True,
                },
            },
            {"key": "motion", "type": "start_continuous_motion", "position": (640.0, 0.0), "properties": {"x": 420.0, "y": 0.0}},
        ),
        "edges": (
            ("key", "next", "create", "in", "flow"),
            ("create", "next", "motion", "in", "flow"),
        ),
    },
    {
        "id": "scrolling_road_or_sky",
        "topics": ("Movement", "Image", "Background"),
        "title": "Create Moving Background or Road",
        "category": "Image & Background",
        "summary": "Repeats a background texture and scrolls it continuously without moving the object or its collider.",
        "keywords": "background scroll road sky cloud stars parallax image texture repeat",
        "steps": (
            "Place a Sprite Renderer on the background and adjust its size in the Scene View.",
            "Select the image in the Start Scrolling Background block; tileable images work best.",
            "For a road, use Y=160 and repeat Y. For sky, use X=25 and repeat X.",
            "Parallax 0.3 creates a far layer; 1.0 keeps normal speed.",
            "The Transform and collider remain stationary; only the texture scrolls.",
        ),
        "nodes": (
            {"key": "start", "type": "event_start", "position": (0.0, 0.0)},
            {
                "key": "scroll", "type": "start_texture_scroll", "position": (290.0, 0.0),
                "properties": {
                    "path": "", "speed_x": 0.0, "speed_y": 160.0,
                    "repeat_x": False, "repeat_y": True, "parallax": 1.0,
                    "send_to_background": True,
                },
            },
        ),
        "edges": (("start", "next", "scroll", "in", "flow"),),
    },
    {
        "id": "move_x_every_frame",
        "topics": ("Movement", "Position"),
        "title": "Move Automatically on X Axis",
        "category": "Position & Movement",
        "summary": "Moves the object continuously to the right without requiring key presses.",
        "keywords": "move walk automatic x right each frame speed velocity",
        "steps": (
            "Triggers the flow on every frame.",
            "Move By adds 120 units per second to the X axis.",
            "Use a negative value in X to move to the left.",
        ),
        "nodes": (
            {"key": "update", "type": "event_update", "position": (0.0, 0.0)},
            {"key": "move", "type": "move_by", "position": (270.0, 0.0), "properties": {"x": 120.0, "y": 0.0}},
        ),
        "edges": (("update", "next", "move", "in", "flow"),),
    },
    {
        "id": "press_d_start_permanent_x",
        "topics": ("Movement", "Position", "Input"),
        "title": "Press D Once to Keep Walking",
        "category": "Input & Movement",
        "summary": "Pressing D once initiates a continuous motion on the X axis that persists after releasing the key.",
        "keywords": "d press once permanent infinite movement keep walk x key release",
        "steps": (
            "On Key Pressed triggers only on the transition from released to pressed.",
            "Start Continuous Motion saves the X velocity in the runtime.",
            "The object continues moving after D is released.",
            "Use Stop Continuous Motion on another event to halt it.",
        ),
        "nodes": (
            {"key": "key", "type": "event_key_pressed", "position": (0.0, 0.0), "properties": {"key": "D"}},
            {"key": "motion", "type": "start_continuous_motion", "position": (300.0, 0.0), "properties": {"x": 120.0, "y": 0.0}},
        ),
        "edges": (("key", "next", "motion", "in", "flow"),),
    },
    {
        "id": "controlled_permanent_motion",
        "topics": ("Movement", "Position", "Input", "Debug"),
        "title": "Control Permanent Motion",
        "category": "Position & Movement",
        "summary": "Starts a named continuous motion and allows modifying, pausing, resuming, or stopping only that specific motion.",
        "keywords": "permanent movement name accelerate decelerate local global pause resume change stop query",
        "steps": (
            "On Start creates the movement 'Run' with smooth acceleration and deceleration.",
            "The Shift key updates the speed without creating another motion.",
            "P pauses only 'Run', and R resumes from where it left off.",
            "S performs a smooth stop using the configured deceleration.",
            "Use Get Continuous Motion to read speed, direction, pause state, and active status.",
        ),
        "nodes": (
            {"key": "start", "type": "event_start", "position": (0.0, 0.0)},
            {
                "key": "motion", "type": "start_continuous_motion", "position": (300.0, 0.0),
                "properties": {
                    "movement": "Run", "x": 120.0, "y": 0.0, "space": "global",
                    "acceleration": 240.0, "deceleration": 360.0,
                },
            },
            {"key": "shift", "type": "event_key_pressed", "position": (0.0, 190.0), "properties": {"key": "LSHIFT"}},
            {
                "key": "faster", "type": "update_continuous_motion", "position": (300.0, 190.0),
                "properties": {"movement": "Run", "x": 260.0, "y": 0.0, "acceleration": 300.0},
            },
            {"key": "pause_key", "type": "event_key_pressed", "position": (0.0, 380.0), "properties": {"key": "P"}},
            {"key": "pause", "type": "pause_continuous_motion", "position": (300.0, 380.0), "properties": {"movement": "Run"}},
            {"key": "resume_key", "type": "event_key_pressed", "position": (0.0, 570.0), "properties": {"key": "R"}},
            {"key": "resume", "type": "resume_continuous_motion", "position": (300.0, 570.0), "properties": {"movement": "Run"}},
            {"key": "stop_key", "type": "event_key_pressed", "position": (0.0, 760.0), "properties": {"key": "S"}},
            {"key": "stop", "type": "stop_continuous_motion", "position": (300.0, 760.0), "properties": {"movement": "Run", "smooth": True}},
        ),
        "edges": (
            ("start", "next", "motion", "in", "flow"),
            ("shift", "next", "faster", "in", "flow"),
            ("pause_key", "next", "pause", "in", "flow"),
            ("resume_key", "next", "resume", "in", "flow"),
            ("stop_key", "next", "stop", "in", "flow"),
        ),
    },
    {
        "id": "move_y_every_frame",
        "topics": ("Movement", "Position"),
        "title": "Move Automatically on Y Axis",
        "category": "Position & Movement",
        "summary": "Moves the object continuously downwards without using the keyboard.",
        "keywords": "move walk automatic y down up each frame speed velocity",
        "steps": (
            "Triggers the movement on every frame.",
            "Move By adds 120 units per second to the Y axis.",
            "Use a negative value in Y to move upwards.",
        ),
        "nodes": (
            {"key": "update", "type": "event_update", "position": (0.0, 0.0)},
            {"key": "move", "type": "move_by", "position": (270.0, 0.0), "properties": {"x": 0.0, "y": 120.0}},
        ),
        "edges": (("update", "next", "move", "in", "flow"),),
    },
    {
        "id": "set_initial_position",
        "topics": ("Position",),
        "title": "Set Position on Start",
        "category": "Position & Movement",
        "summary": "Places the object at specific coordinates when Play mode starts.",
        "keywords": "initial position start spawn teleport x y on start",
        "steps": (
            "On Start triggers only once.",
            "Set Position immediately overrides the X and Y coordinates.",
            "Edit X and Y in the node properties.",
        ),
        "nodes": (
            {"key": "start", "type": "event_start", "position": (0.0, 0.0)},
            {"key": "position", "type": "set_position", "position": (270.0, 0.0), "properties": {"x": 100.0, "y": 100.0}},
        ),
        "edges": (("start", "next", "position", "in", "flow"),),
    },
    {
        "id": "create_object_on_start",
        "topics": ("Objects", "Creation"),
        "title": "Create Object on Start",
        "category": "Objects & Scene",
        "summary": "Creates a new object when Play mode starts, allowing references to it in subsequent blocks.",
        "keywords": "create object spawn instantiate new image position size color",
        "steps": (
            "On Start triggers only once.",
            "Create Object deep-copies visual properties, components, and attributes from the template.",
            "The copy is independent: changes to it do not affect the original template.",
            "The Object output port can connect to Move, Rotate, Set Sprite, or Destroy.",
            "Check Relative Position to offsets X and Y from the current object.",
        ),
        "nodes": (
            {"key": "start", "type": "event_start", "position": (0.0, 0.0)},
            {"key": "create", "type": "create_object", "position": (270.0, 0.0)},
        ),
        "edges": (("start", "next", "create", "in", "flow"),),
    },
    {
        "id": "spawn_prefab_on_key",
        "topics": ("Objects", "Creation", "Input"),
        "title": "Create Prefab on Space Press",
        "category": "Objects & Scene",
        "summary": "Instantiates a complete Prefab whenever the Spacebar is pressed.",
        "keywords": "create prefab spawn projectile shoot key space instantiate component",
        "steps": (
            "Triggers the check on every frame.",
            "Key Pressed yields flow only during the frame the key was pressed down.",
            "Create Prefab instantiates rendering, colliders, rigidbodies, audio, and UI from the file.",
            "Select the .zprefab file and check Relative Position if needed.",
        ),
        "nodes": (
            {"key": "update", "type": "event_update", "position": (0.0, 0.0)},
            {"key": "key", "type": "key_pressed", "position": (270.0, 0.0), "properties": {"key": "SPACE"}},
            {"key": "prefab", "type": "create_prefab", "position": (540.0, 0.0), "properties": {"path": "Assets/Prefabs/Projectile.zprefab", "relative": True}},
        ),
        "edges": (
            ("update", "next", "key", "in", "flow"),
            ("key", "true", "prefab", "in", "flow"),
        ),
    },
    {
        "id": "patrol_y_between_limits",
        "topics": ("Movement", "Position"),
        "title": "Patrol Y Axis Between Limits",
        "category": "Position & Movement",
        "summary": "Moves continuously on the Y axis and reverses direction when reaching 100 or -100.",
        "keywords": "patrol ping pong reverse direction limit y negative 100 positive 100 automatic",
        "steps": (
            "Triggers the patrol on every frame.",
            "The object starts moving up the Y axis until it reaches the 100 limit.",
            "Upon reaching 100, it reverses; at -100, it reverses again.",
            "Speed controls the units traveled per second.",
            "Y axis patrol overrides gravity calculations on this axis.",
        ),
        "nodes": (
            {"key": "update", "type": "event_update", "position": (0.0, 0.0)},
            {"key": "patrol", "type": "patrol_axis", "position": (270.0, 0.0), "properties": {"axis": "Y", "minimum": -100.0, "maximum": 100.0, "speed": 100.0}},
        ),
        "edges": (("update", "next", "patrol", "in", "flow"),),
    },
    {
        "id": "patrol_x_between_limits",
        "topics": ("Movement", "Position"),
        "title": "Patrol X Axis Between Limits",
        "category": "Position & Movement",
        "summary": "Creates a platform or enemy that patrols back and forth along the X axis.",
        "keywords": "patrol platform enemy ping pong reverse direction limit x",
        "steps": (
            "Triggers the patrol on every frame.",
            "The X axis is constrained between -200 and 200.",
            "Edit minimum, maximum, and speed in the node properties.",
        ),
        "nodes": (
            {"key": "update", "type": "event_update", "position": (0.0, 0.0)},
            {"key": "patrol", "type": "patrol_axis", "position": (270.0, 0.0), "properties": {"axis": "X", "minimum": -200.0, "maximum": 200.0, "speed": 120.0}},
        ),
        "edges": (("update", "next", "patrol", "in", "flow"),),
    },
)
