from typing import Any

LOGIC_RECIPES_PART_2 = (
    {
        "id": "show_x_on_hud",
        "topics": ("Position", "Text"),
        "title": "Show X Position on HUD",
        "category": "Position & Movement",
        "summary": "Reads the current position of the object and displays the X coordinate on the HUD.",
        "keywords": "read position coordinate x hud text debug show",
        "steps": (
            "Triggers the text update on every frame.",
            "Get Position retrieves the current coordinates of the object.",
            "Convert to Text transforms the X coordinate, and Update HUD displays it.",
        ),
        "nodes": (
            {"key": "update", "type": "event_update", "position": (0.0, 0.0)},
            {"key": "position", "type": "get_position", "position": (0.0, 180.0)},
            {"key": "text", "type": "to_text", "position": (270.0, 180.0)},
            {"key": "hud", "type": "set_hud", "position": (540.0, 0.0)},
        ),
        "edges": (
            ("update", "next", "hud", "in", "flow"),
            ("position", "x", "text", "value", "number"),
            ("text", "value", "hud", "text", "text"),
        ),
    },
    {
        "id": "sprite_on_start",
        "topics": ("Action", "Objects"),
        "title": "Change Sprite on Start",
        "category": "Image & Sprite",
        "summary": "Binds an image asset and applies it to the object when Play mode begins.",
        "keywords": "image sprite texture png jpg swap bind on start",
        "steps": (
            "On Start triggers only once.",
            "Select Set Object Sprite and choose a project asset.",
            "Pick a PNG, JPG, BMP, or WEBP from the Assets folder.",
        ),
        "nodes": (
            {"key": "start", "type": "event_start", "position": (0.0, 0.0)},
            {"key": "sprite", "type": "set_sprite", "position": (270.0, 0.0)},
        ),
        "edges": (("start", "next", "sprite", "in", "flow"),),
    },
    {
        "id": "animation_asset_on_start",
        "topics": ("Action",),
        "title": "Play Animation on Start",
        "category": "Animation",
        "summary": "Binds and plays a .zanim animation file immediately when Play mode begins.",
        "keywords": "animation animate zanim frames sprite sheet start bind",
        "steps": (
            "On Start triggers only once.",
            "Select Play Animation File and bind a .zanim from Assets.",
            "The engine loads and plays the animation clip automatically.",
        ),
        "nodes": (
            {"key": "start", "type": "event_start", "position": (0.0, 0.0)},
            {"key": "animation", "type": "play_animation_asset", "position": (270.0, 0.0)},
        ),
        "edges": (("start", "next", "animation", "in", "flow"),),
    },
    {
        "id": "sound_on_start",
        "topics": ("Action",),
        "title": "Play Sound on Start",
        "category": "Audio",
        "summary": "Binds a sound asset and plays it once when Play mode begins.",
        "keywords": "sound audio music effect wav ogg mp3 start bind",
        "steps": (
            "On Start triggers only once.",
            "Select Play Sound and choose a project asset.",
            "Choose a WAV, OGG, MP3, or FLAC file from the Assets folder.",
        ),
        "nodes": (
            {"key": "start", "type": "event_start", "position": (0.0, 0.0)},
            {"key": "sound", "type": "play_sound", "position": (270.0, 0.0)},
        ),
        "edges": (("start", "next", "sound", "in", "flow"),),
    },
    {
        "id": "sound_on_collision",
        "topics": ("Events", "Action"),
        "title": "Play Sound on Collision",
        "category": "Collision & Audio",
        "summary": "Plays a sound effect whenever the object begins colliding with something.",
        "keywords": "collision hit impact sound effect event collider",
        "steps": (
            "On Collision Enter is triggered by the physics engine.",
            "Play Sound reproduces the selected asset.",
            "The object must have an active Collider component.",
        ),
        "nodes": (
            {"key": "collision", "type": "event_collision_enter", "position": (0.0, 0.0)},
            {"key": "sound", "type": "play_sound", "position": (270.0, 0.0)},
        ),
        "edges": (("collision", "next", "sound", "in", "flow"),),
    },
    {
        "id": "jump_with_space",
        "topics": ("Movement", "Condition"),
        "title": "Jump on Space Press",
        "category": "Input & Movement",
        "summary": "Checks the Spacebar state every frame and triggers a jump only if pressed.",
        "keywords": "jump space key condition input movement",
        "steps": (
            "Triggers the check on every frame.",
            "Key Pressed yields True flow only on the frame the key goes down.",
            "Jump applies the configured force if the object is grounded.",
        ),
        "nodes": (
            {"key": "update", "type": "event_update", "position": (0.0, 0.0)},
            {"key": "key", "type": "key_pressed", "position": (270.0, 0.0), "properties": {"key": "SPACE"}},
            {"key": "jump", "type": "jump", "position": (540.0, 0.0), "properties": {"force": 420.0}},
        ),
        "edges": (
            ("update", "next", "key", "in", "flow"),
            ("key", "true", "jump", "in", "flow"),
        ),
    },
    {
        "id": "timer_console_message",
        "topics": ("Events",),
        "title": "Trigger Action on Timer Interval",
        "category": "Time & Events",
        "summary": "Uses a repeating timer to output a message to the Console.",
        "keywords": "timer time second repeat event console message",
        "steps": (
            "After a Delay ticks at 1.0 second and repeats.",
            "Log to Console outputs a confirmation message.",
            "Replace the final block with any desired action.",
        ),
        "nodes": (
            {"key": "timer", "type": "event_timer", "position": (0.0, 0.0), "properties": {"seconds": 1.0, "repeat": True}},
            {"key": "log", "type": "log_message", "position": (270.0, 0.0), "properties": {"text": "One second passed"}},
        ),
        "edges": (("timer", "next", "log", "in", "flow"),),
    },
    {
        "id": "if_else_example",
        "topics": ("Logic", "Condition"),
        "title": "Choose Between Two Actions",
        "category": "Logic & Conditions",
        "summary": "Demonstrates how to split execution paths based on a boolean condition.",
        "keywords": "if else true false decision condition logic",
        "steps": (
            "On Start enters the If / Else block.",
            "True and False paths run completely independent blocks.",
            "Edit the Condition parameter in properties to test both paths.",
        ),
        "nodes": (
            {"key": "start", "type": "event_start", "position": (0.0, 0.0)},
            {"key": "branch", "type": "if_else", "position": (270.0, 0.0), "properties": {"condition": True}},
            {"key": "yes", "type": "log_message", "position": (540.0, -80.0), "properties": {"text": "Condition is true"}},
            {"key": "no", "type": "log_message", "position": (540.0, 100.0), "properties": {"text": "Condition is false"}},
        ),
        "edges": (
            ("start", "next", "branch", "in", "flow"),
            ("branch", "true", "yes", "in", "flow"),
            ("branch", "false", "no", "in", "flow"),
        ),
    },
    {
        "id": "find_and_hide_tag",
        "topics": ("Objects",),
        "title": "Find Object by Tag and Disable",
        "category": "Objects & Scene",
        "summary": "Searches for an object with a specific tag and disables it during runtime.",
        "keywords": "object search find tag hide disable scene",
        "steps": (
            "Find by Tag locates the first active object with that tag.",
            "The object output port sends the reference to Enable / Disable.",
            "Edit the Target Tag and Active properties in the node panel.",
        ),
        "nodes": (
            {"key": "start", "type": "event_start", "position": (0.0, 0.0)},
            {"key": "find", "type": "find_tag", "position": (270.0, 0.0), "properties": {"tag": "Enemy"}},
            {"key": "active", "type": "set_active", "position": (540.0, 0.0), "properties": {"active": False}},
        ),
        "edges": (
            ("start", "next", "find", "in", "flow"),
            ("find", "next", "active", "in", "flow"),
            ("find", "object", "active", "target", "object"),
        ),
    },
    {
        "id": "store_starting_health",
        "topics": ("Variables",),
        "title": "Create Health Variable",
        "category": "Variables",
        "summary": "Saves an initial Health variable on the object with a value of 100.",
        "keywords": "variable health points value store set",
        "steps": (
            "On Start triggers only once.",
            "Number node outputs the value 100.0.",
            "Set Variable stores 'Health' on the object scope.",
        ),
        "nodes": (
            {"key": "start", "type": "event_start", "position": (0.0, 0.0)},
            {"key": "number", "type": "number_value", "position": (0.0, 180.0), "properties": {"value": 100.0}},
            {"key": "set", "type": "set_variable", "position": (270.0, 0.0), "properties": {"scope": "object", "name": "Health", "value": 100.0}},
        ),
        "edges": (
            ("start", "next", "set", "in", "flow"),
            ("number", "value", "set", "value", "number"),
        ),
    },
    {
        "id": "math_to_hud",
        "topics": ("Math",),
        "title": "Add Numbers and Show on HUD",
        "category": "Math & HUD",
        "summary": "Adds two numbers, converts the sum to text, and displays it on screen.",
        "keywords": "add math numbers sum convert hud",
        "steps": (
            "Add calculates A plus B from input ports or properties.",
            "Convert to Text transforms the numeric value to a string.",
            "Update HUD displays the result string on screen.",
        ),
        "nodes": (
            {"key": "start", "type": "event_start", "position": (0.0, 0.0)},
            {"key": "add", "type": "add_number", "position": (0.0, 180.0), "properties": {"a": 10.0, "b": 5.0}},
            {"key": "text", "type": "to_text", "position": (270.0, 180.0)},
            {"key": "hud", "type": "set_hud", "position": (540.0, 0.0)},
        ),
        "edges": (
            ("start", "next", "hud", "in", "flow"),
            ("add", "value", "text", "value", "number"),
            ("text", "value", "hud", "text", "text"),
        ),
    },
    {
        "id": "join_text_to_hud",
        "topics": ("Text",),
        "title": "Join Texts and Show on HUD",
        "category": "Text & HUD",
        "summary": "Combines two pieces of text and displays the resulting phrase on screen.",
        "keywords": "text concatenate phrase name hud UI",
        "steps": (
            "Join Texts combines inputs A and B.",
            "The output value port enters the HUD text property.",
            "Edit both input strings to customize your message.",
        ),
        "nodes": (
            {"key": "start", "type": "event_start", "position": (0.0, 0.0)},
            {"key": "join", "type": "join_text", "position": (0.0, 180.0), "properties": {"a": "Hello, ", "b": "player!"}},
            {"key": "hud", "type": "set_hud", "position": (320.0, 0.0)},
        ),
        "edges": (
            ("start", "next", "hud", "in", "flow"),
            ("join", "value", "hud", "text", "text"),
        ),
    },
)
